trigger: none

schedules:
  - cron: "0 22 * * *" #UTC TIME! mm HH DD MM DW
    displayName: Daily after-midnight test runner build
    branches:
      include:
      - masters/NPR_BC16_W1

resources:
  repositories:
  - repository: scriptsRepo
    type: git
    name:  'NpCore/NpDevOps'

pool:
  name: NP Core Additional Validation Pipelines
  demands: 
  - docker
  # Now only 2019 is available but in the future it will be every newer version.
  # Then we will probably remove this requirement as it will alwyas TRUE.
  - Agent.OS -equals Windows_NT
  - Agent.OSVersion -equals 10.0.17763

jobs:
- template: YAML/Templates/Job/BuildALApp.yml@scriptsRepo
  parameters:
    timeoutInMinutes: 180
    containerImageName: mcr.microsoft.com/dynamicsnav:10.0.17763.1397-generic
    artifactURL: https://bcartifacts.azureedge.net/onprem/16.4.14693.15090/w1 
    containerName: Build-$(Build.BuildId)
    serverInstanceName: BC
    containerAdminUsername: admin
    containerAdminPassword: P@ssword1
    licenseSecureFileName: 'DEV_BC OP 16.flf'
    scriptsRepo: ScriptsRepo
    dependancyPackages:
      - source: 'https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/navipartner/_packaging/NprAddIns/nuget/v3/index.json'
        id: NaviPartner.NPRetail.AddIns.BC #CASE SENSITIVE!
    alternativeSystemALPackages:
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.au
        ISOcountryCode: AU
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.dk
        ISOcountryCode: DK
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.fr
        ISOcountryCode: FR
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.gb
        ISOcountryCode: GB
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.it
        ISOcountryCode: IT
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.na
        ISOcountryCode: NA
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.nl
        ISOcountryCode: NL
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.no
        ISOcountryCode: NO
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.nz
        ISOcountryCode: NZ
      - packages:
        - source: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
          id: Microsoft.BC.160.Base_Application.se
        ISOcountryCode: SE