trigger: none

schedules:
  - cron: "0 18 28 * *" #UTC TIME! mm HH DD MM DW
    displayName: Daily after-midnight AppSource Validation build
    branches:
      include:
      - master

resources:
  repositories:
  - repository: scriptsRepo
    type: git
    name: 'NpCore/NpDevOps'

jobs:
- job: CreateNewMajorRelease
  
  pool:
    name: 'NP BuildServers'
    demands: 
    - docker
    - Agent.OS -equals Windows_NT
  
  variables:
    StagingHostPath: C:\AzureDevOps\Staging\$(Build.BuildId)\$(System.StageName)
    StagingContainerPath: C:/Staging

  displayName: Create new major release

  steps:
  - template: /YAML/Templates/Step/DownloadScriptsFromRepo.yml@scriptsRepo
    parameters:
      scriptsRepo: scriptsRepo
      path: $(StagingHostPath)/Scripts

  - task: PowerShell@2
    inputs:
      filePath: $(SetupScriptVars.psScriptsFolder)/BuildDeploy/CreateReleaseBranch.ps1
      arguments: >
        -RepositoryId '$(Build.Repository.ID)'
        -ReleaseBranchFolderPath 'refs/heads/releases/'
        -SourceBranch '$(Build.SourceBranch)'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)          
    displayName: 'Create new release branch'
    retryCountOnTaskFailure: 3
