trigger: none

schedules:
  - cron: "0 20 * * *" #UTC TIME! mm HH DD MM DW
    displayName: Daily after-midnight test runner build
    branches:
      include:
      - masters/NPR_BC17_W1
    
resources:
  repositories:
  - repository: scriptsRepo
    type: git
    name: 'NpCore/NpDevOps'
    ref: 'refs/heads/releases/1.0'

pool:
  name: NP Core Pipelines
  demands: 
  - docker
  # Now only 2019 is available but in the future it will be every newer version.
  # Then we will probably remove this requirement as it will alwyas TRUE.
  - Agent.OS -equals Windows_NT
  - Agent.OSVersion -equals 10.0.17763

jobs:
- template: YAML/Templates/Build/TestRunnerBuild.yml@scriptsRepo
  parameters:
    testApps:
    - name: Microsoft_Tests-Misc
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Misc.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-MISC.json'
      #disabledTests: '@{CodeunitName = "Page Troubleshooting Test"; Method = "*"},@{CodeunitName = "Profile Import/Export Test"; Method = "*"}' # skip CU138696 and CU138697 because of session issues
    - name: Microsoft_Tests-Bank
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Bank.app'
    - name: Microsoft_Tests-Cash_Flow
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Cash Flow.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-CASH FLOW.json'
    - name: Microsoft_Tests-Cost_Accounting
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Cost Accounting.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-COST ACCOUNTING.json'
    - name: Microsoft_Tests-CRM_integration
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-CRM integration.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-CRM INtEGRATION.json'
    - name: Microsoft_Tests-Data_Exchange
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Data Exchange.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-DATA EXCHANGE.json'
    - name: Microsoft_Tests-Dimension
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Dimension.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-DIMENSION.json'
    - name: Microsoft_Tests-ERM
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-ERM.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-ERM.json'      
    - name: Microsoft_Tests-Fixed_Asset
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Fixed Asset.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-FIXED ASSETS.json'      
    - name: Microsoft_Tests-General_Journal
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-General Journal.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-GENERAL JOURNAL.json'      
    - name: Microsoft_Tests-Graph
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Graph.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-GRAPH.json'            
    - name: Microsoft_Tests-Integration
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Integration.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-INTEGRATION.json'      
    - name: Microsoft_Tests-Invoicing
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Invoicing.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-INVOICING.json'      
    - name: Microsoft_Tests-Job
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Job.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-JOB.json'      
    - name: Microsoft_Tests-Local
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Local.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-LOCAL.json'      
    - name: Microsoft_Tests-Marketing
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Marketing.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-MARKETING.json'
    - name: Microsoft_Tests-Permissions
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Permissions.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-PERMISSIONS.json'      
    - name: Microsoft_Tests-Physical_Inventory
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Physical Inventory.app'      
    - name: Microsoft_Tests-Prepayment
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Prepayment.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-PREPAYMENT.json'      
    - name: Microsoft_Tests-Rapid_Start
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Rapid Start.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-RAPID START.json'      
    - name: Microsoft_Tests-Report
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Report.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-REPORT.json'     
    - name: Microsoft_Tests-Resource
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Resource.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-RESOURCE.json'      
    - name: Microsoft_Tests-Reverse
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Reverse.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-REVERSE.json'      
    - name: Microsoft_Tests-SCM
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-SCM.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-SCM.json'      
    # - name: Microsoft_Tests-SINGLESERVER
    #   appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-SINGLESERVER.app' Freddy always skips this app in his scripts?!
    - name: Microsoft_Tests-SMB
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-SMB.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-SMB.json'      
    - name: Microsoft_Tests-SMTP
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-SMTP.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-SMTP.json'      
    - name: Microsoft_Tests-Upgrade
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Upgrade.app'
    - name: Microsoft_Tests-User
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-User.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-USER.json'      
    - name: Microsoft_Tests-VAT
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-VAT.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-VAT.json'      
    - name: Microsoft_Tests-Workflow
      appPath: 'C:\Applications\baseapp\test\Microsoft_Tests-Workflow.app'
      disabledTestsJsonFile: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/DevOps/DisabledTests/DisabledTests-WORKFLOW.json'      

    dependancies:
    - appsToDeploy:
      - path: 'C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app'
      - path: 'C:\Applications\TestFramework\TestLibraries\Any\Microsoft_Any.app'      
      - path: 'C:\Applications\TestFramework\TestLibraries\Assert\Microsoft_Library Assert.app'
      - path: 'C:\Applications\TestFramework\TestLibraries\Variable Storage\Microsoft_Library Variable Storage.app'
      - path: 'C:\Applications\system application\test\Microsoft_System Application Test Library.app'      
      - path: 'C:\Applications\baseapp\test\Microsoft_Tests-TestLibraries.app'            
    - package:
        source: 'https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/navipartner/_packaging/NprAddIns/nuget/v3/index.json'
        id: NaviPartner.NPRetail.AddIns.BC #CASE SENSITIVE!
        destinationPath: '$(ServiceTierFolder)/Add-Ins'    
    - package:
        source: 'https://pkgs.dev.azure.com/navipartner/_packaging/NpCore/nuget/v3/index.json'
        id: NaviPartner.NPCore.BC$(majorVersion)
        destinationPath: '$(Agent.TempDirectory)/NpRetail/'
      appsToDeploy:
        - path: '$(Agent.TempDirectory)/NpRetail/Np_Retail.app'              
    - package:
        source: 'https://pkgs.dev.azure.com/navipartner/_packaging/NPCoreTestFixture/nuget/v3/index.json'
        id: NaviPartner.NPCore.TestFixture.BC160
        destinationPath: '$(Agent.TempDirectory)/TestFixture/'
      appsToDeploy:
        - path: '$(Agent.TempDirectory)/TestFixture/Test_Fixture_Initializer.app'