resources:
  repositories:
  - repository: NPDevOps
    type: git
    name: NPCore/NpDevOps 
  - repository: NPCoreTranslationsRepository
    type: git
    name: NPCore/NpCore-Translations

trigger:
  batch: true
  branches:
    include:
    - masters/NPR_BC16_W1
  paths:
    include:
    - Translations/NP Retail.g.xlf

pool:
  name: NP Deployment
  
steps:
- checkout: self
  persistCredentials: true
  clean: true

- template: /YAML/Templates/Step/DownloadScriptsFromRepo.yml@NpDevOps
  parameters:
    scriptsRepo: NpDevOps

- task: PowerShell@2
  inputs:
    filePath: $(psScriptsFolder)\BuildDeploy\PushTranslationToRepo.ps1
    arguments: >
      -TranslationRepoName NpCore-Translations
      -TranslationFilePath '$(Build.SourcesDirectory)\$(Build.Repository.Name)\Translations\NP Retail.g.xlf'
      -StyleSheetFilePath '$(ScriptsRootFolder)\transformations\sort_trans-unit.xsl'
      -CommitComment 'Testing commit'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: 'Push translation to the repository'

