trigger: none

schedules:
  - cron: "0 22 * * *" #UTC TIME! mm HH DD MM DW
    displayName: Daily after-midnight AppSource Validation build
    branches:
      include:
      - master

resources:
  repositories:
  - repository: scriptsRepo
    type: git
    name: 'NpCore/NpDevOps'
    ref: 'refs/heads/releases/1.0'

pool:
  name: NP Core Pipelines
  demands: 
  - docker
  # Now only 2019 is available but in the future it will be every newer version.
  # Then we will probably remove this requirement as it will alwyas TRUE.
  - Agent.OS -equals Windows_NT
  - Agent.OSVersion -equals 10.0.17763

jobs:
- template: YAML/Templates/Build/AppSourceValidationBuild.yml@scriptsRepo
  parameters:
    appNuGetSource:
      source: 'https://pkgs.dev.azure.com/navipartner/_packaging/NpCore/nuget/v3/index.json'
      id: NaviPartner.NPCore.BC$(majorVersion)
      download:
        enabled: true
        deployApp: true
    dependancies:
    - package:
        source: 'https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/navipartner/_packaging/NprAddIns/nuget/v3/index.json'
        id: NaviPartner.NPRetail.AddIns.BC #CASE SENSITIVE!
        destinationPath: '$(ServiceTierFolder)/Add-Ins'