trigger: none

schedules:
  - cron: "0 20 * * *" #UTC TIME! mm HH DD MM DW
    displayName: Daily after-midnight AppSource Validation build
    branches:
      include:
      - master

resources:
  repositories:
  - repository: scriptsRepo
    type: git
    name: 'NpCore/NpDevOps'

stages:
- template: /YAML/ZAL Build Definitions/AppSourceValidationBuild.yml@scriptsRepo
  parameters:
    pool:
      name: 'NP BuildServers'
      demands: 
      - docker
      - Agent.OS -equals Windows_NT
    
    generatePermissions:
      enabled: true
      alObjectsFolder: $(Build.Repository.LocalPath)/Application/src/
      destinationFileName: /Permissions/NPRETAIL.PermissionSet.al
      objectId: 6014400
      objectName: 'NPR NP RETAIL'
      objectCaption: 'NP Retail'
      xmlRoleId: 'NP RETAIL'
      xmlRoleName: 'NP Retail'         
    outputLogExcludeFilters:
    - (?=^[\w\W]*(AL0432):[\w\W]*)(?!^[\w\W]*AL0432:[\w\W]*(Tag:[\w\W]*))