trigger: none

resources:
  repositories:
  - repository: scriptsRepo
    type: git
    name:  'NpCore/NpDevOps'

pool:
  name: NP Core Pipelines

variables: 
  url: https://bcartifacts.blob.core.windows.net/onprem/17.0.16993.0
  feed: 'https://pkgs.dev.azure.com/navipartner/_packaging/BCSymbols/nuget/v3/index.json'
  packageId: Microsoft.BC.170
  containerName: Build-$(Build.BuildId)
  serverInstanceName: BC
  containerAdminUsername: admin
  containerAdminPassword: P@ssword1  

jobs:
- template: YAML/Templates/Job/CreateBCContainer.yml@scriptsRepo
  parameters:
    timeoutInMinutes: 180
    containerImageName: mcr.microsoft.com/dynamicsnav:10.0.17763.1397-generic
    artifactUrl: $(url)/w1
    containerName: $(containerName)
    serverInstanceName: $(serverInstanceName)
    containerAdminUsername: $(username) 
    containerAdminPassword: $(password)
    licenseSecureFileName: 'DEV_BC OP 17.flf'
    scriptsRepo: scriptsRepo
    stepList:
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            Import-Module (Join-Path -Path $env:ServiceTierFolder -ChildPath 'Microsoft.Dynamics.Nav.Management.dll') -WarningAction SilentlyContinue
            $nstInfo = get-navserverinstance -serverInstance $(serverInstanceName)
            Write-Host "##vso[task.setvariable variable=nstVersion]$($nstInfo.Version)"   
        displayName: 'Read NST properties'

      - template: YAML/Templates/Step/GenerateAndPublishPackage.yml@scriptsRepo
        parameters:
          version: $(nstVersion)
          description: AddIns for Microsoft Dynamics Business Central
          authors: navipartner
          files:
          - '$(ServiceTierFolder)\Add-ins\**\*.*'
          publishToSource: 
            source: 'https://pkgs.dev.azure.com/navipartner/_packaging/NprAddIns/nuget/v3/index.json'
            id: NaviPartner.NPRetail.AddIns.MS.BC
          continueOnPublishError: true

- template: YAML/Templates/Job/PopulateSymbolFeeds.yml@scriptsRepo
  parameters:
    timeoutInMinutes: 180
    scriptsRepo: scriptsRepo
    symbolPackages:
    - name: at #Country
      url: $(url)/at #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.at #Country
      feed: $(feed)

    - name: au #Country
      url: $(url)/au #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.au #Country
      feed: $(feed)

    - name: be #Country
      url: $(url)/be #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.be #Country
      feed: $(feed)      

    - name: ca #Country
      url: $(url)/ca #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.ca #Country
      feed: $(feed)

    - name: ch #Country
      url: $(url)/ch #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.ch #Country
      feed: $(feed)

    - name: cz #Country
      url: $(url)/cz #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.cz #Country
      feed: $(feed)

    - name: de #Country
      url: $(url)/de #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.de #Country
      feed: $(feed)      

    - name: dk #Country
      url: $(url)/dk #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.dk #Country
      - sourcePath: \Applications\OIOUBL\Source\OIOUBL.Source.zip
        appPath: \Applications\OIOUBL\Source\Microsoft_OIOUBL.app
        packageId: $(packageId).OIOUBL.dk #Country        
      feed: $(feed)

    - name: es #Country
      url: $(url)/es #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.es #Country
      feed: $(feed)

    - name: fi #Country
      url: $(url)/fi #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.fi #Country
      feed: $(feed)

    - name: fr #Country
      url: $(url)/fr #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.fr #Country
      feed: $(feed)

    - name: gb #Country
      url: $(url)/gb #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.gb #Country
      feed: $(feed)

    - name: is #Country
      url: $(url)/is #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.is #Country
      feed: $(feed)

    - name: it #Country
      url: $(url)/it #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.it #Country
      feed: $(feed)
      
    - name: mx #Country
      url: $(url)/mx #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.mx #Country
      feed: $(feed)      

    - name: nl #Country
      url: $(url)/nl #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.nl #Country
      feed: $(feed)
      
    - name: no #Country
      url: $(url)/no #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.no #Country
      feed: $(feed)

    - name: nz #Country
      url: $(url)/nz #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.nz #Country
      feed: $(feed)

    # - name: ru #Country
    #   url: $(url)/ru #Country
    #   appPackages:
    #   - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
    #     appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
    #     packageId: $(packageId).Base_Application.ru #Country
    #   feed: $(feed)
     
    - name: se #Country
      url: $(url)/se #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.se #Country
      feed: $(feed)      

    - name: us #Country
      url: $(url)/us #Country
      appPackages:
      - sourcePath: \Applications\BaseApp\Source\Base Application.Source.zip
        appPath: \Applications\BaseApp\Source\Microsoft_Base Application.app
        packageId: $(packageId).Base_Application.us #Country
      feed: $(feed)