export const NotificationType = {
    INFO: "NOTIFICATION.TYPE.INFO",
    WARNING: "NOTIFICATION.TYPE.WARNING",
    ERROR: "NOTIFICATION.TYPE.ERROR"
};

export const NotificationUpdateType = {
    MINIMIZE: "NOTIFICATION.UPDATE.MINIMIZE",
    HIDE_TOAST: "NOTIFICATION.UPDATE.HIDE_TOAST",
    SNOOZE: "NOTIFICATION.UPDATE.SNOOZE",
    SHOW: "NOTIFICATION.UPDATE.SHOW",
    COMPLETE: "NOTIFICATION.UPDATE.COMPLETE",
    NEVER_AGAIN: "NOTIFICATION.UPDATE.NEVER_AGAIN"
};

export const NotificationState = {
    TOAST: "NOTIFICATION.STATE.TOAST",
    TOAST_HIDING: "NOTIFICATION.STATE.TOAST_HIDING",
    MINIMIZED: "NOTIFICATION.STATE.MINIMIZED",
    SNOOZED: "NOTIFICATION.STATE.SNOOZED",
    IGNORED: "NOTIFICATION.STATE.IGNORED",
    COMPLETED: "NOTIFICATION.STATE.COMPLETED"
};

export const DEFAULT_TOAST_SCREEN_TIME_SECONDS = 15;
