# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  globalApiTypes: ./../global-api-types.yml

types:
  ItemId:
    type: string
    docs: The unique identifier for an item.

  Item:
    docs: Represents an inventory item in the system.
    properties:
      id: uuid
      code: string
      description: string
      description2: string
      baseUnitOfMeasure: string
      itemDiscGroup: string
      itemCategoryCode: string
      vatProdPostingGroup: string
      unitPrice: double
      vendorNo: string
      vendorItemNo: string
      inventory: double
      hasVariants: boolean
      rowVersion: string
      attributes: optional<map<string, unknown>>
    examples:
      - name: ExampleItem
        value:
          id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          code: "A1000"
          description: "Office Chair"
          description2: "Ergonomic Design"
          baseUnitOfMeasure: "PCS"
          itemDiscGroup: "FURNITURE"
          itemCategoryCode: "CHAIR"
          vatProdPostingGroup: "STANDARD"
          unitPrice: 4000
          vendorNo: "01587796"
          vendorItemNo: "ADG-4577"
          inventory: 42.0
          hasVariants: true
          rowVersion: "12345678901234567890"
          attributes:
            Color: "Black"
            Depth: 70
            Width: 75
            Height: 100
            Material Description: "Leather, Satin Polished Aluminum base"

  ListItem:
    docs: Represents an inventory item in the system.
    properties:
      id: uuid
      code: string
      description: string
      description2: string
      baseUnitOfMeasure: string
      itemDiscGroup: string
      itemCategoryCode: string
      vatProdPostingGroup: string
      unitPrice: double
      vendorNo: string
      vendorItemNo: string
      rowVersion: optional<string>
      attributes: optional<map<string, unknown>>
    examples:
      - name: ExampleItem
        value:
          id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          code: "A1000"
          description: "Office Chair"
          description2: "Ergonomic Design"
          baseUnitOfMeasure: "PCS"
          itemDiscGroup: "FURNITURE"
          itemCategoryCode: "CHAIR"
          vatProdPostingGroup: "STANDARD"
          unitPrice: 4000
          vendorNo: "01587796"
          vendorItemNo: "ADG-4577"
          rowVersion: "12345678901234567890"
          attributes:
            Color: "Black"
            Depth: 70
            Width: 75
            Height: 100
            Material Description: "Leather, Satin Polished Aluminum base"

  PaginatedItems:
    docs: A paginated response containing multiple items
    properties:
      morePages: boolean
      nextPageKey: string
      nextPageURL: string
      data: list<ListItem>
    examples:
      - name: ExamplePaginatedItems
        value:
          morePages: true
          nextPageKey: "c29tZSBiYXNlNjQgc3RyaW5n"
          nextPageURL: "https://api.npretail.app/tenant/env/company/inventory/item?pageKey=c29tZSBiYXNlNjQgc3RyaW5n&lastRowVersion=12345678901234567890"
          data:
            - $ListItem.ExampleItem
            - $ListItem.ExampleItem

service:
  auth: true
  display-name: Item Service
  base-path: /inventory
  endpoints:
    getItem:
      display-name: Get Item
      docs: Get an item by its code
      method: GET
      path: "/item/{id}"
      path-parameters:
        id: ItemId
      request:
        name: getItemRequest
        query-parameters:
          withAttributes:
            type: optional<boolean>
            docs: Indicates whether the item attributes should be included in the response.
      response: Item
      examples:
        - path-parameters:
            tenant: $globalApiTypes.tenant.Exampletenant
            environment: $globalApiTypes.environment.ExampleenvironmentProduction
            company: $globalApiTypes.Company.ExampleCompanyCronus
            id: "A1000"
          query-parameters:
            withAttributes: true
          response:
            body: $Item.ExampleItem

    getItems:
      display-name: Get Items
      docs: Get a list of items with pagination
      method: GET
      path: "/item"
      request:
        name: getItemsRequest
        query-parameters:
          itemCode: optional<string>
          pageSize: optional<integer>
          pageKey: optional<string>
          lastRowVersion: optional<string>
          sync: optional<boolean>
          withAttributes:
            type: optional<boolean>
            docs: Indicates whether the item attributes should be included in the response.
      response: PaginatedItems
      examples:
        - path-parameters:
            tenant: $globalApiTypes.tenant.Exampletenant
            environment: $globalApiTypes.environment.ExampleenvironmentProduction
            company: $globalApiTypes.Company.ExampleCompanyCronus
          query-parameters:
            pageSize: 50
            withAttributes: true
          response:
            body: $PaginatedItems.ExamplePaginatedItems