# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  globalApiTypes: ./../global-api-types.yml

types:
  ItemCategory:
    docs: Represents an item category in the system.
    properties:
      id: uuid
      code: string
      description: string
      parentCode: string
      presentationOrder: integer
      hasChildren: boolean
      indentation: integer
      rowVersion: optional<string>
    examples:
      - name: ExampleItemCategory
        value:
          id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          code: "FURNITURE"
          description: "Furniture"
          parentCode: "OFFICE"
          presentationOrder: 100
          hasChildren: true
          indentation: 1
          rowVersion: "12345678901234567890"
          
  PaginatedItemCategories:
    docs: A paginated response containing multiple item categories
    properties:
      morePages: boolean
      nextPageKey: string
      nextPageURL: string
      data: list<ItemCategory>
    examples:
      - name: ExamplePaginatedItemCategories
        value:
          morePages: true
          nextPageKey: "c29tZSBiYXNlNjQgc3RyaW5n"
          nextPageURL: "https://api.npretail.app/tenant/env/company/inventory/itemcategory?pageKey=c29tZSBiYXNlNjQgc3RyaW5n&lastRowVersion=12345678901234567890"
          data:
            - $ItemCategory.ExampleItemCategory
            - $ItemCategory.ExampleItemCategory

service:
  auth: true
  display-name: Item Category Service
  base-path: /inventory
  endpoints:
    getItemCategories:
      display-name: Get Item Categories
      docs: Get a list of item categories with pagination
      method: GET
      path: "/itemcategory"
      request:
        name: getItemCategoriesRequest
        query-parameters:
          pageSize: optional<integer>
          pageKey: optional<string>
          lastRowVersion: optional<string>
          sync: optional<boolean>
      response: PaginatedItemCategories
      examples:
        - path-parameters:
            tenant: $globalApiTypes.tenant.Exampletenant
            environment: $globalApiTypes.environment.ExampleenvironmentProduction
            company: $globalApiTypes.Company.ExampleCompanyCronus
          query-parameters:
            pageSize: 50
          response:
            body: $PaginatedItemCategories.ExamplePaginatedItemCategories