table 6151550 "NPR NpXml Setup"
{
    // NC1.17/MH/20150622  CASE 216851 Object Created - NpXml specific fields from NaviConnect Setup
    // NC1.21/TTH/20151020 CASE 224528 Adding versioning. Added field 50
    // NC1.21/MHA/20151110 CASE 227051 Added seo formatting to autogenerated Username
    // NC1.22/MHA/20151211 CASE 229473 Updated Automatic Username functionality and deleted function ReplaceSpecialChar()
    // NC2.00/MHA/20160525  CASE 240005 NaviConnect

    Caption = 'NpXml Setup';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Primary Key"; Code[10])
        {
            Caption = 'Primary Key';
            DataClassification = CustomerContent;
        }
        field(10; "NpXml Enabled"; Boolean)
        {
            Caption = 'NpXml Enabled';
            DataClassification = CustomerContent;
        }
        field(60; "Template Version Prefix"; Code[5])
        {
            Caption = 'Template Version Prefix';
            DataClassification = CustomerContent;
            Description = 'NC1.21';

            trigger OnValidate()
            begin
                if (StrPos("Template Version Prefix", 'NC') = 1) then
                    Error(Text100);
            end;
        }
        field(65; "Template Version No."; Integer)
        {
            Caption = 'Template Version No.';
            DataClassification = CustomerContent;
            Description = 'NC1.21';
            InitValue = 1;
            MinValue = 1;
            NotBlank = true;
        }
    }

    keys
    {
        key(Key1; "Primary Key")
        {
        }
    }

    fieldgroups
    {
    }

    var
        Text100: Label 'Invalid version tag';
}

