table 6150684 "NPR NPRE Color Table"
{
    Caption = 'Color Table';
    DataClassification = CustomerContent;
    LookupPageId = "NPR NPRE Color Table";
    DrillDownPageID = "NPR NPRE Color Table";

    fields
    {
        field(10; Description; Text[30])
        {
            Caption = 'Description';
            DataClassification = CustomerContent;
        }
        field(20; "RGB Color Code (Hex)"; Code[6])
        {
            Caption = 'RGB Color Code (Hex)';
            DataClassification = CustomerContent;
        }
    }

    keys
    {
        key(PK; Description)
        {
            Clustered = true;
        }
    }

    procedure InitializeTable(Force: Boolean)
    var
        NPREColorTable: Record "NPR NPRE Color Table";
    begin
        if not (NPREColorTable.IsEmpty() OR Force) then
            exit;

        InsertColor('000000', 'Black');
        InsertColor('0C090A', 'Night');
        InsertColor('2c3539', 'Gunmetal');
        InsertColor('2b1b17', 'Midnight');
        InsertColor('34282c', 'Charcoal');
        InsertColor('25383c', 'Dark Slate Grey');
        InsertColor('3b3131', 'Oil');
        InsertColor('413839', 'Black Cat');
        InsertColor('3D3C3A', 'Iridium');
        InsertColor('463e3f', 'Black Eel');
        InsertColor('4c4646', 'Black Cow');
        InsertColor('504a4b', 'Gray Wolf');
        InsertColor('565051', 'Vampire Gray');
        InsertColor('5c5858', 'Gray Dolphin');
        InsertColor('625D5D', 'Carbon Gray');
        InsertColor('666362', 'Ash Gray');
        InsertColor('6d6968', 'Cloudy Gray');
        InsertColor('726e6d', 'Smokey Gray');
        InsertColor('736f6e', 'Gray');
        InsertColor('837E7C', 'Granite');
        InsertColor('848482', 'Battleship Gray');
        InsertColor('B6B6B4', 'Gray Cloud');
        InsertColor('D1D0CE', 'Gray Goose');
        InsertColor('E5E4E2', 'Platinum');
        InsertColor('BCC6CC', 'Metallic Silver');
        InsertColor('98afc7', 'Blue Gray');
        InsertColor('6d7b8d', 'Light Slate Gray');
        InsertColor('657383', 'Slate Gray');
        InsertColor('616d7e', 'Jet Gray');
        InsertColor('646d7e', 'Mist Blue');
        InsertColor('566d7e', 'Marble Blue');
        InsertColor('737ca1', 'Slate Blue');
        InsertColor('4863a0', 'Steel Blue');
        InsertColor('2b547e', 'Blue Jay');
        InsertColor('2b3856', 'Dark Slate Blue');
        InsertColor('151b54', 'Midnight Blue');
        InsertColor('000080', 'Navy Blue');
        InsertColor('342d7e', 'Blue Whale');
        InsertColor('15317e', 'Lapis Blue');
        InsertColor('151b8d', 'Denim Dark Blue');
        InsertColor('0000A0', 'Earth Blue');
        InsertColor('0020C2', 'Cobalt Blue');
        InsertColor('0041C2', 'Blueberry Blue');
        InsertColor('2554c7', 'Sapphire Blue');
        InsertColor('1569c7', 'Blue Eyes');
        InsertColor('2b60de', 'Royal Blue');
        InsertColor('1F45FC', 'Blue Orchid');
        InsertColor('6960ec', 'Blue Lotus');
        InsertColor('736aff', 'Light Slate Blue');
        InsertColor('357ec7', 'Windows Blue');
        InsertColor('368BC1', 'Glacial Blue Ice');
        InsertColor('488ac7', 'Silk Blue');
        InsertColor('3090c7', 'Blue Ivy');
        InsertColor('659ec7', 'Blue Koi');
        InsertColor('87afc7', 'Columbia Blue');
        InsertColor('95b9c7', 'Baby Blue');
        InsertColor('728fce', 'Light Steel Blue');
        InsertColor('2b65ec', 'Ocean Blue');
        InsertColor('306eff', 'Blue Ribbon');
        InsertColor('157dec', 'Blue Dress');
        InsertColor('1589ff', 'Dodger Blue');
        InsertColor('6495ED', 'Cornflower Blue');
        InsertColor('6698ff', 'Sky Blue');
        InsertColor('38acec', 'Butterfly Blue');
        InsertColor('56a5ec', 'Iceberg');
        InsertColor('5cb3ff', 'Crystal Blue');
        InsertColor('3bb9ff', 'Deep Sky Blue');
        InsertColor('79baec', 'Denim Blue');
        InsertColor('82cafa', 'Light Sky Blue');
        InsertColor('82caff', 'Day Sky Blue');
        InsertColor('a0cfec', 'Jeans Blue');
        InsertColor('b7ceec', 'Blue Angel');
        InsertColor('b4cfec', 'Pastel Blue');
        InsertColor('c2dfff', 'Sea Blue');
        InsertColor('c6deff', 'Powder Blue');
        InsertColor('afdcec', 'Coral Blue');
        InsertColor('addfff', 'Light Blue');
        InsertColor('bdedff', 'Robin Egg Blue');
        InsertColor('CFECEC', 'Pale Blue Lily');
        InsertColor('e0ffff', 'Light Cyan');
        InsertColor('EBF4FA', 'Water');
        InsertColor('F0F8FF', 'AliceBlue');
        InsertColor('F0FFFF', 'Azure');
        InsertColor('CCFFFF', 'Light Slate');
        InsertColor('93FFE8', 'Light Aquamarine');
        InsertColor('9afeff', 'Electric Blue');
        InsertColor('7FFFD4', 'Aquamarine');
        InsertColor('00ffff', 'Cyan or Aqua');
        InsertColor('7DFDFE', 'Tron Blue');
        InsertColor('57feff', 'Blue Zircon');
        InsertColor('8eebec', 'Blue Lagoon');
        InsertColor('50ebec', 'Celeste');
        InsertColor('4ee2ec', 'Blue Diamond');
        InsertColor('81D8D0', 'Tiffany Blue');
        InsertColor('92c7c7', 'Cyan Opaque');
        InsertColor('77bfc7', 'Blue Hosta');
        InsertColor('78C7C7', 'Northern Lights Blue');
        InsertColor('48cccd', 'Medium Turquoise');
        InsertColor('43c6db', 'Turquoise');
        InsertColor('46c7c7', 'Jellyfish');
        InsertColor('7bccb5', 'Blue green');
        InsertColor('43bfc7', 'Macaw Blue Green');
        InsertColor('3EA99F', 'Light Sea Green');
        InsertColor('3b9c9c', 'Dark Turquoise');
        InsertColor('438D80', 'Sea Turtle Green');
        InsertColor('348781', 'Medium Aquamarine');
        InsertColor('307D7E', 'Greenish Blue');
        InsertColor('5e7d7e', 'Grayish Turquoise');
        InsertColor('4c787e', 'Beetle Green');
        InsertColor('008080', 'Teal');
        InsertColor('4e8975', 'Sea Green');
        InsertColor('78866B', 'Camouflage Green');
        InsertColor('848b79', 'Sage Green');
        InsertColor('617c58', 'Hazel Green');
        InsertColor('728C00', 'Venom Green');
        InsertColor('667c26', 'Fern Green');
        InsertColor('254117', 'Dark Forest Green');
        InsertColor('306754', 'Medium Sea Green');
        InsertColor('347235', 'Medium Forest Green');
        InsertColor('437c17', 'Seaweed Green');
        InsertColor('387c44', 'Pine Green');
        InsertColor('347c2c', 'Jungle Green');
        InsertColor('347c17', 'Shamrock Green');
        InsertColor('348017', 'Medium Spring Green');
        InsertColor('4e9258', 'Forest Green');
        InsertColor('6AA121', 'Green Onion');
        InsertColor('4aa02c', 'Spring Green');
        InsertColor('41a317', 'Lime Green');
        InsertColor('3EA055', 'Clover Green');
        InsertColor('6CBB3C', 'Green Snake');
        InsertColor('6cc417', 'Alien Green');
        InsertColor('4cc417', 'Green Apple');
        InsertColor('52d017', 'Yellow Green');
        InsertColor('4cc552', 'Kelly Green');
        InsertColor('54c571', 'Zombie Green');
        InsertColor('99c68e', 'Frog Green');
        InsertColor('89C35C', 'Green Peas');
        InsertColor('85BB65', 'Dollar Bill Green');
        InsertColor('8bb381', 'Dark Sea Green');
        InsertColor('9CB071', 'Iguana Green');
        InsertColor('B2C248', 'Avocado Green');
        InsertColor('9DC209', 'Pistachio Green');
        InsertColor('A1C935', 'Salad Green');
        InsertColor('7fe817', 'Hummingbird Green');
        InsertColor('59e817', 'Nebula Green');
        InsertColor('57e964', 'Stoplight Go Green');
        InsertColor('64e986', 'Algae Green');
        InsertColor('5efb6e', 'Jade Green');
        InsertColor('00ff00', 'Green');
        InsertColor('5ffb17', 'Emerald Green');
        InsertColor('87f717', 'Lawn Green');
        InsertColor('8afb17', 'Chartreuse');
        InsertColor('6afb92', 'Dragon Green');
        InsertColor('98FF98', 'Mint green');
        InsertColor('b5eaaa', 'Green Thumb');
        InsertColor('c3fdb8', 'Light Jade');
        InsertColor('ccfb5d', 'Tea Green');
        InsertColor('b1fb17', 'Green Yellow');
        InsertColor('bce954', 'Slime Green');
        InsertColor('edda74', 'Goldenrod');
        InsertColor('ede275', 'Harvest Gold');
        InsertColor('ffe87c', 'Sun Yellow');
        InsertColor('ffff00', 'Yellow');
        InsertColor('fff380', 'Corn Yellow');
        InsertColor('FFFFC2', 'Parchment');
        InsertColor('FFFFCC', 'Cream');
        InsertColor('fff8c6', 'Lemon Chiffon');
        InsertColor('FFF8DC', 'Cornsilk');
        InsertColor('F5F5DC', 'Beige');
        InsertColor('FBF6D9', 'Blonde');
        InsertColor('FAEBD7', 'AntiqueWhite');
        InsertColor('F7E7CE', 'Champagne');
        InsertColor('FFEBCD', 'BlanchedAlmond');
        InsertColor('F3E5AB', 'Vanilla');
        InsertColor('ece5b6', 'Tan Brown');
        InsertColor('FFE5B4', 'Peach');
        InsertColor('FFDB58', 'Mustard');
        InsertColor('FFD801', 'Rubber Ducky Yellow');
        InsertColor('fdd017', 'Bright Gold');
        InsertColor('eac117', 'Golden brown');
        InsertColor('F2BB66', 'Macaroni and Cheese');
        InsertColor('fbb917', 'Saffron');
        InsertColor('fbb117', 'Beer');
        InsertColor('FFA62F', 'Cantaloupe');
        InsertColor('e9ab17', 'Bee Yellow');
        InsertColor('E2A76F', 'Brown Sugar');
        InsertColor('DEB887', 'BurlyWood');
        InsertColor('FFCBA4', 'Deep Peach');
        InsertColor('c9be62', 'Ginger Brown');
        InsertColor('e8a317', 'School Bus Yellow');
        InsertColor('ee9a4d', 'Sandy Brown');
        InsertColor('c8b560', 'Fall Leaf Brown');
        InsertColor('d4a017', 'Orange Gold');
        InsertColor('C2B280', 'Sand');
        InsertColor('c7a317', 'Cookie Brown');
        InsertColor('c68e17', 'Caramel');
        InsertColor('B5A642', 'Brass');
        InsertColor('ada96e', 'Khaki');
        InsertColor('C19A6B', 'Camel brown');
        InsertColor('CD7F32', 'Bronze');
        InsertColor('C88141', 'Tiger Orange');
        InsertColor('c58917', 'Cinnamon');
        InsertColor('AF9B60', 'Bullet Shell');
        InsertColor('af7817', 'Dark Goldenrod');
        InsertColor('B87333', 'Copper');
        InsertColor('966F33', 'Wood');
        InsertColor('806517', 'Oak Brown');
        InsertColor('827839', 'Moccasin');
        InsertColor('827b60', 'Army Brown');
        InsertColor('786D5F', 'Sandstone');
        InsertColor('493D26', 'Mocha');
        InsertColor('483C32', 'Taupe');
        InsertColor('6F4E37', 'Coffee');
        InsertColor('835C3B', 'Brown Bear');
        InsertColor('7f5217', 'Red Dirt');
        InsertColor('7f462c', 'Sepia');
        InsertColor('c47451', 'Orange Salmon');
        InsertColor('c36241', 'Rust');
        InsertColor('c35817', 'Red Fox');
        InsertColor('c85a17', 'Chocolate');
        InsertColor('CC6600', 'Sedona');
        InsertColor('e56717', 'Papaya Orange');
        InsertColor('e66c2c', 'Halloween Orange');
        InsertColor('f87217', 'Pumpkin Orange');
        InsertColor('f87431', 'Construction Cone Orange');
        InsertColor('e67451', 'Sunrise Orange');
        InsertColor('FF8040', 'Mango Orange');
        InsertColor('f88017', 'Dark Orange');
        InsertColor('FF7F50', 'Coral');
        InsertColor('f88158', 'Basket Ball Orange');
        InsertColor('f9966b', 'Light Salmon');
        InsertColor('e78a61', 'Tangerine');
        InsertColor('e18b6b', 'Dark Salmon');
        InsertColor('e77471', 'Light Coral');
        InsertColor('f75d59', 'Bean Red');
        InsertColor('e55451', 'Valentine Red');
        InsertColor('e55b3c', 'Shocking Orange');
        InsertColor('ff0000', 'Red');
        InsertColor('FF2400', 'Scarlet');
        InsertColor('f62217', 'Ruby Red');
        InsertColor('F70D1A', 'Ferrari Red');
        InsertColor('f62817', 'Fire Engine Red');
        InsertColor('e42217', 'Lava Red');
        InsertColor('e41b17', 'Love Red');
        InsertColor('DC381F', 'Grapefruit');
        InsertColor('C34A2C', 'Chestnut Red');
        InsertColor('c24641', 'Cherry Red');
        InsertColor('C04000', 'Mahogany');
        InsertColor('c11b17', 'Chilli Pepper');
        InsertColor('9F000F', 'Cranberry');
        InsertColor('990012', 'Red Wine');
        InsertColor('8C001A', 'Burgundy');
        InsertColor('954535', 'Chestnut');
        InsertColor('7e3517', 'Blood Red');
        InsertColor('8a4117', 'Sienna');
        InsertColor('7e3817', 'Sangria');
        InsertColor('800517', 'Firebrick');
        InsertColor('810541', 'Maroon');
        InsertColor('7d0541', 'Plum Pie');
        InsertColor('7e354d', 'Velvet Maroon');
        InsertColor('7d0552', 'Plum Velvet');
        InsertColor('7f4e52', 'Rosy Finch');
        InsertColor('7f5a58', 'Puce');
        InsertColor('7f525d', 'Dull Purple');
        InsertColor('b38481', 'Rosy Brown');
        InsertColor('c5908e', 'Khaki Rose');
        InsertColor('c48189', 'Pink Bow');
        InsertColor('c48793', 'Lipstick Pink');
        InsertColor('e8adaa', 'Rose');
        InsertColor('ECC5C0', 'Rose Gold');
        InsertColor('EDC9AF', 'Desert Sand');
        InsertColor('FDD7E4', 'Pig Pink');
        InsertColor('fcdfff', 'Cotton Candy');
        InsertColor('FFDFDD', 'Pink Bubble Gum');
        InsertColor('fbbbb9', 'Misty Rose');
        InsertColor('faafbe', 'Pink');
        InsertColor('faafba', 'Light Pink');
        InsertColor('f9a7b0', 'Flamingo Pink');
        InsertColor('e7a1b0', 'Pink Rose');
        InsertColor('e799a3', 'Pink Daisy');
        InsertColor('E38AAE', 'Cadillac Pink');
        InsertColor('f778a1', 'Carnation Pink');
        InsertColor('e56e94', 'Blush Red');
        InsertColor('F660AB', 'Hot Pink');
        InsertColor('FC6C85', 'Watermelon Pink');
        InsertColor('f6358a', 'Violet Red');
        InsertColor('f52887', 'Deep Pink');
        InsertColor('e45e9d', 'Pink Cupcake');
        InsertColor('e4287c', 'Pink Lemonade');
        InsertColor('F535AA', 'Neon Pink');
        InsertColor('ff00ff', 'Magenta');
        InsertColor('e3319d', 'Dimorphotheca Magenta');
        InsertColor('f433ff', 'Bright Neon Pink');
        InsertColor('d16587', 'Pale Violet Red');
        InsertColor('c25a7c', 'Tulip Pink');
        InsertColor('ca226b', 'Medium Violet Red');
        InsertColor('c12869', 'Rogue Pink');
        InsertColor('c12267', 'Burnt Pink');
        InsertColor('c25283', 'Bashful Pink');
        InsertColor('c12283', 'Dark Carnation Pink');
        InsertColor('b93b8f', 'Plum');
        InsertColor('7e587e', 'Viola Purple');
        InsertColor('571b7e', 'Purple Iris');
        InsertColor('583759', 'Plum Purple');
        InsertColor('4B0082', 'Indigo');
        InsertColor('461B7E', 'Purple Monster');
        InsertColor('4e387e', 'Purple Haze');
        InsertColor('614051', 'Eggplant');
        InsertColor('5e5a80', 'Grape');
        InsertColor('6a287e', 'Purple Jam');
        InsertColor('7d1b7e', 'Dark Orchid');
        InsertColor('A74AC7', 'Purple Flower');
        InsertColor('b048b5', 'Medium Orchid');
        InsertColor('6c2dc7', 'Purple Amethyst');
        InsertColor('842dce', 'Dark Violet');
        InsertColor('8d38c9', 'Violet');
        InsertColor('7a5dc7', 'Purple Sage Bush');
        InsertColor('7f38ec', 'Lovely Purple');
        InsertColor('8e35ef', 'Purple');
        InsertColor('893bff', 'Aztech Purple');
        InsertColor('8467d7', 'Medium Purple');
        InsertColor('A23bec', 'Jasmine Purple');
        InsertColor('b041ff', 'Purple Daffodil');
        InsertColor('c45aec', 'Tyrian Purple');
        InsertColor('9172ec', 'Crocus Purple');
        InsertColor('9e7bff', 'Purple Mimosa');
        InsertColor('d462ff', 'Heliotrope Purple');
        InsertColor('e238ec', 'Crimson');
        InsertColor('c38ec7', 'Purple Dragon');
        InsertColor('C8A2C8', 'Lilac');
        InsertColor('e6a9ec', 'Blush Pink');
        InsertColor('E0B0FF', 'Mauve');
        InsertColor('c6aec7', 'Wisteria Purple');
        InsertColor('f9b7ff', 'Blossom Pink');
        InsertColor('D2B9D3', 'Thistle');
        InsertColor('d9cfec', 'Periwinkle');
        InsertColor('ebdde2', 'Lavender Pinocchio');
        InsertColor('e3e4fa', 'Lavender blue');
        InsertColor('fdeef4', 'Pearl');
        InsertColor('FFF5EE', 'SeaShell');
        InsertColor('FEFCFF', 'Milk White');
        InsertColor('ffffff', 'White');
    END;

    local procedure InsertColor(RGBHexCode: Code[6]; ColorDescription: Text[30])
    var
        NPREColorTable: Record "NPR NPRE Color Table";
    begin

        if not NPREColorTable.GET(ColorDescription) then begin
            NPREColorTable.Description := ColorDescription;
            NPREColorTable.Insert();
        end;

        NPREColorTable."RGB Color Code (Hex)" := RGBHexCode;
        NPREColorTable.Modify();
    end;
}
