codeunit 85488 "NPR DK SAF-T Cash Export Tests"
{
    Subtype = Test;

    var
        _Assert: Codeunit Assert;
        _LibraryInventory: Codeunit "NPR Library - Inventory";
        _LibraryPOSMasterData: Codeunit "NPR Library - POS Master Data";
        _ConfirmReplies: List of [Boolean];
        _ExpectedConfirmQuestions: List of [Text];
        _GenerateImmediatelyQstTxt: Label 'did not schedule the SAF-T file generation', Locked = true;
        _RestartCompletedExportQstTxt: Label 'restart the export to get a new SAF-T file', Locked = true;
        _SAFTNamespaceTxt: Label 'urn:StandardAuditFile-Taxation-CashRegister:DK', Locked = true;

    [Test]
    [HandlerFunctions('ConfirmHandler')]
    [TestPermissions(TestPermissions::Disabled)]
    procedure ExportOverMultipleMonthsProducesOneCompleteXmlFile()
    var
        Item: Record Item;
        POSStore: Record "NPR POS Store";
        POSUnit: Record "NPR POS Unit";
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
        NamespaceManager: XmlNamespaceManager;
        Document: XmlDocument;
        Root: XmlElement;
        Nodes: XmlNodeList;
        StartingDate: Date;
        EndingDate: Date;
    begin
        // [SCENARIO] SKAT technical description v2.0 requires one complete XML file for the requested period.
        Initialize();

        // [GIVEN] A POS unit with fiscal cash transactions in two different months and an item in master data
        StartingDate := DMY2Date(1, 1, Date2DMY(WorkDate(), 3));
        EndingDate := CalcDate('<CM+1M>', StartingDate);
        CreatePOSStoreAndUnit(POSStore, POSUnit);
        CreateFiscalPOSEntry(POSStore.Code, POSUnit."No.", StartingDate + 4, 'DKFISC-1', 125);
        CreateFiscalPOSEntry(POSStore.Code, POSUnit."No.", EndingDate - 2, 'DKFISC-2', 250);
        _LibraryInventory.CreateItem(Item);
        CreateExportHeader(SAFTExportHeader, StartingDate, EndingDate, false);

        // [WHEN] The export is run in the foreground and the user confirms immediate generation
        EnqueueConfirm(_GenerateImmediatelyQstTxt, true);
        Codeunit.Run(Codeunit::"NPR DK SAF-T Cash Export Mgt.", SAFTExportHeader);

        // [THEN] Exactly one export line exists and the export completed
        SAFTExportHeader.Find();
        _Assert.AreEqual(SAFTExportHeader.Status::Completed, SAFTExportHeader.Status, 'The export must complete.');
        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        _Assert.AreEqual(1, SAFTExportLine.Count(), 'The export must produce exactly one SAF-T file.');
        SAFTExportLine.FindFirst();
        _Assert.AreEqual(SAFTExportLine.Status::Completed, SAFTExportLine.Status, 'The export line must complete.');
        _Assert.AreEqual(StartingDate, SAFTExportLine."Starting Date", 'The single file must start on the requested starting date.');
        _Assert.AreEqual(EndingDate, SAFTExportLine."Ending Date", 'The single file must end on the requested ending date.');

        // [THEN] The file holds header, master data and both months' transactions in one auditfile document
        ReadExportedXml(SAFTExportLine, Document, NamespaceManager);
        Document.GetRoot(Root);
        _Assert.AreEqual('auditfile', Root.LocalName(), 'The root element must be auditfile.');
        _Assert.AreEqual(1, CountNodes(Document, NamespaceManager, '/s:auditfile/s:header'), 'The file must contain one header.');
        _Assert.AreEqual(1, CountNodes(Document, NamespaceManager, '/s:auditfile/s:company'), 'The file must contain one company.');
        _Assert.AreEqual(
            1, CountNodes(Document, NamespaceManager, StrSubstNo('/s:auditfile/s:company/s:articles/s:article[s:artID=''%1'']', Item."No.")),
            'Master data (articles) must be in the same file as the transactions.');

        Document.SelectNodes(
            StrSubstNo('/s:auditfile/s:company/s:location/s:cashregister[s:registerID=''%1'']/s:cashtransaction/s:transID', POSUnit."No."),
            NamespaceManager, Nodes);
        _Assert.AreEqual(2, Nodes.Count(), 'Transactions from both months must be in the same file.');
        _Assert.AreEqual(
            1, CountNodes(Document, NamespaceManager, '//s:cashtransaction[s:transID=''DKFISC-1'']'), 'The first month transaction must be exported.');
        _Assert.AreEqual(
            1, CountNodes(Document, NamespaceManager, '//s:cashtransaction[s:transID=''DKFISC-2'']'), 'The second month transaction must be exported.');

        AssertAllConfirmsRaised();
    end;

    [Test]
    [HandlerFunctions('ConfirmHandler')]
    [TestPermissions(TestPermissions::Disabled)]
    procedure RestartingLegacySplitExportReplacesFilesWithOneFile()
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
    begin
        // [SCENARIO] An export generated by the old logic (master data + per-month files) is regenerated as one file.
        Initialize();

        // [GIVEN] A completed export with three legacy lines
        CreateLegacySplitExport(SAFTExportHeader, 3);

        // [WHEN] The export is restarted and the user confirms both the restart and immediate generation
        EnqueueConfirm(_RestartCompletedExportQstTxt, true);
        EnqueueConfirm(_GenerateImmediatelyQstTxt, true);
        Codeunit.Run(Codeunit::"NPR DK SAF-T Cash Export Mgt.", SAFTExportHeader);

        // [THEN] Only one line remains and it holds a generated file
        VerifySingleGeneratedFile(SAFTExportHeader, 'Restarting must replace the split files with one SAF-T file.');

        AssertAllConfirmsRaised();
    end;

    [Test]
    [TestPermissions(TestPermissions::Disabled)]
    procedure DownloadOfLegacySplitExportIsRefused()
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
        SAFTExportMgt: Codeunit "NPR DK SAF-T Cash Export Mgt.";
    begin
        // [SCENARIO] Split files from the old logic cannot be downloaded, because SKAT does not accept them.
        Initialize();

        // [GIVEN] A completed export with two legacy lines
        CreateLegacySplitExport(SAFTExportHeader, 2);

        // [WHEN] The file is downloaded
        asserterror SAFTExportMgt.DownloadSAFTFile(SAFTExportHeader);

        // [THEN] The user is told to restart the export
        _Assert.ExpectedError('Restart the export to generate a single SAF-T file.');
    end;

    [Test]
    [TestPermissions(TestPermissions::Disabled)]
    procedure DownloadOfLegacyMasterDataOnlyExportIsRefused()
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
        SAFTExportMgt: Codeunit "NPR DK SAF-T Cash Export Mgt.";
    begin
        // [SCENARIO] An old split export over a period without POS entries has only the master-data line. It is not a complete journal.
        Initialize();

        // [GIVEN] A completed export with only the legacy master-data line
        CreateLegacySplitExport(SAFTExportHeader, 1);

        // [WHEN] The file is downloaded
        asserterror SAFTExportMgt.DownloadSAFTFile(SAFTExportHeader);

        // [THEN] The user is told the export holds only master data and must be restarted
        _Assert.ExpectedError('contains only master data');
    end;

    [Test]
    [HandlerFunctions('ConfirmHandler')]
    [TestPermissions(TestPermissions::Disabled)]
    procedure RestartActionOnLegacyDownloadErrorRegeneratesOneFile()
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
        SAFTExportMgt: Codeunit "NPR DK SAF-T Cash Export Mgt.";
        RestartError: ErrorInfo;
    begin
        // [SCENARIO] The Restart export action on the legacy download error regenerates the export as one file.
        Initialize();

        // [GIVEN] A completed export with two legacy lines, and the error raised when downloading it
        CreateLegacySplitExport(SAFTExportHeader, 2);
        RestartError.RecordId := SAFTExportHeader.RecordId();

        // [WHEN] The user chooses the Restart export action and confirms both questions
        EnqueueConfirm(_RestartCompletedExportQstTxt, true);
        EnqueueConfirm(_GenerateImmediatelyQstTxt, true);
        SAFTExportMgt.RestartExportFromErrorInfo(RestartError);

        // [THEN] The export now holds one generated file
        VerifySingleGeneratedFile(SAFTExportHeader, 'The Restart export action must regenerate the export as one SAF-T file.');

        AssertAllConfirmsRaised();
    end;

    [Test]
    [TestPermissions(TestPermissions::Disabled)]
    procedure DownloadWithoutGeneratedFileIsRefused()
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
        SAFTExportMgt: Codeunit "NPR DK SAF-T Cash Export Mgt.";
    begin
        // [SCENARIO] Downloading before the file is generated gives a clear error.
        Initialize();

        // [GIVEN] An export that was never started
        CreateExportHeader(SAFTExportHeader, WorkDate(), WorkDate(), false);

        // [WHEN] The file is downloaded
        asserterror SAFTExportMgt.DownloadSAFTFile(SAFTExportHeader);

        // [THEN] No file is available
        _Assert.ExpectedError('No SAF-T file has been generated.');
    end;

    [Test]
    [TestPermissions(TestPermissions::Disabled)]
    procedure BackgroundExportSchedulesOneDanishGeneratorTask()
    var
        ScheduledTask: Record "Scheduled Task";
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
    begin
        // [SCENARIO] A background export schedules one task running the Danish generator, not the Norwegian one.
        Initialize();

        // [GIVEN] An export set to run in the background in the future, so no confirmation is asked
        CreateExportHeader(SAFTExportHeader, DMY2Date(1, 1, Date2DMY(WorkDate(), 3)), DMY2Date(31, 12, Date2DMY(WorkDate(), 3)), true);
        SAFTExportHeader."Earliest Start Date/Time" := CreateDateTime(Today() + 30, 0T);
        SAFTExportHeader.Modify();

        // [WHEN] The export is started
        Codeunit.Run(Codeunit::"NPR DK SAF-T Cash Export Mgt.", SAFTExportHeader);

        // [THEN] One line is scheduled with the Danish generator codeunit
        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        _Assert.AreEqual(1, SAFTExportLine.Count(), 'A background export must create one line.');
        SAFTExportLine.FindFirst();
        _Assert.IsTrue(ScheduledTask.Get(SAFTExportLine."Task ID"), 'A task must be scheduled for the export line.');
        _Assert.AreEqual(Codeunit::"NPR DK Gen. SAF-T Cash File", ScheduledTask."Run Codeunit", 'The task must run the Danish SAF-T generator.');
        _Assert.AreEqual(Codeunit::"NPR DK SAF-T Exp. Err. Handler", ScheduledTask."Failure Codeunit", 'The task must use the Danish error handler.');

        // [CLEANUP]
        TaskScheduler.CancelTask(SAFTExportLine."Task ID");
    end;

    [Test]
    [TestPermissions(TestPermissions::Disabled)]
    procedure FileNameMarksTheOnlyFile()
    var
        SAFTXMLHelper: Codeunit "NPR DK SAF-T XML Helper";
    begin
        // [SCENARIO] SKAT file naming: the file number must be 1_1 because output is always a single file.
        _Assert.AreEqual(
            'SAF-T Cash Register_12345678_20260515234556_1_1.xml',
            SAFTXMLHelper.GetFilePath('12345678', CreateDateTime(DMY2Date(15, 5, 2026), 234556T), 1, 1),
            'The file name must follow the SKAT naming standard for a single file.');
        _Assert.AreEqual(
            'SAF-T Cash Register_12345678_20260515090507_1_1.xml',
            SAFTXMLHelper.GetFilePath('12345678', CreateDateTime(DMY2Date(15, 5, 2026), 090507T), 1, 1),
            'The hour in the file name must be zero-padded to two digits.');
    end;

    local procedure Initialize()
    begin
        Clear(_ExpectedConfirmQuestions);
        Clear(_ConfirmReplies);
        EnsureDKFiscalizationSetup();
    end;

    local procedure EnsureDKFiscalizationSetup()
    var
        DKFiscalizationSetup: Record "NPR DK Fiscalization Setup";
    begin
        if not DKFiscalizationSetup.Get() then begin
            DKFiscalizationSetup.Init();
            DKFiscalizationSetup.Insert();
        end;
        DKFiscalizationSetup."SAF-T Contact No." := 'DKSAFTTEST';
        DKFiscalizationSetup."SAF-T Audit File Sender" := '';
        DKFiscalizationSetup.Modify();
    end;

    local procedure EnqueueConfirm(ExpectedQuestion: Text; Reply: Boolean)
    begin
        _ExpectedConfirmQuestions.Add(ExpectedQuestion);
        _ConfirmReplies.Add(Reply);
    end;

    local procedure AssertAllConfirmsRaised()
    begin
        _Assert.AreEqual(0, _ExpectedConfirmQuestions.Count(), 'Not every expected confirmation was raised.');
    end;

    local procedure CreateExportHeader(var SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header"; StartingDate: Date; EndingDate: Date; RunInBackground: Boolean)
    begin
        SAFTExportHeader.Init();
        SAFTExportHeader.Insert(true);
        SAFTExportHeader."Starting Date" := StartingDate;
        SAFTExportHeader."Ending Date" := EndingDate;
        SAFTExportHeader."Parallel Processing" := RunInBackground;
        SAFTExportHeader.Modify();
    end;

    local procedure CreateLegacySplitExport(var SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header"; NoOfLines: Integer)
    var
        LineNo: Integer;
    begin
        CreateExportHeader(SAFTExportHeader, WorkDate(), WorkDate(), false);
        for LineNo := 1 to NoOfLines do
            InsertLegacyLine(SAFTExportHeader, LineNo, LineNo = 1);
        SAFTExportHeader.Status := SAFTExportHeader.Status::Completed;
        SAFTExportHeader.Modify();
    end;

    local procedure InsertLegacyLine(SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header"; LineNo: Integer; MasterData: Boolean)
    var
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
        OutStr: OutStream;
    begin
        SAFTExportLine.Init();
        SAFTExportLine.ID := SAFTExportHeader.ID;
        SAFTExportLine."Line No." := LineNo;
        SAFTExportLine.Status := SAFTExportLine.Status::Completed;
#pragma warning disable AL0432
        SAFTExportLine."Master Data" := MasterData;
#pragma warning restore AL0432
        SAFTExportLine."Starting Date" := SAFTExportHeader."Starting Date";
        SAFTExportLine."Ending Date" := SAFTExportHeader."Ending Date";
        SAFTExportLine."SAF-T File".CreateOutStream(OutStr, TextEncoding::UTF8);
        OutStr.WriteText('<auditfile/>');
        SAFTExportLine.Insert();
    end;

    local procedure CreatePOSStoreAndUnit(var POSStore: Record "NPR POS Store"; var POSUnit: Record "NPR POS Unit")
    var
        POSPostingProfile: Record "NPR POS Posting Profile";
        POSSetup: Record "NPR POS Setup";
    begin
        _LibraryPOSMasterData.CreatePOSSetup(POSSetup);
        _LibraryPOSMasterData.CreateDefaultPostingSetup(POSPostingProfile);
        _LibraryPOSMasterData.CreatePOSStore(POSStore, POSPostingProfile.Code);
        _LibraryPOSMasterData.CreatePOSUnit(POSUnit, POSStore.Code, POSPostingProfile.Code);
    end;

    local procedure CreateFiscalPOSEntry(POSStoreCode: Code[10]; POSUnitNo: Code[10]; EntryDate: Date; FiscalNo: Code[20]; AmountInclTax: Decimal)
    var
        POSEntry: Record "NPR POS Entry";
    begin
        // No library helper creates a finished fiscal POS entry without running a full POS sale.
        POSEntry.Init();
        POSEntry."POS Store Code" := POSStoreCode;
        POSEntry."POS Unit No." := POSUnitNo;
        POSEntry."Entry Type" := POSEntry."Entry Type"::"Direct Sale";
        POSEntry."Entry Date" := EntryDate;
        POSEntry."Starting Time" := 120000T;
        POSEntry."Fiscal No." := FiscalNo;
        POSEntry."Amount Incl. Tax" := AmountInclTax;
        POSEntry."Amount Excl. Tax" := Round(AmountInclTax / 1.25);
        POSEntry.Insert();
    end;

    local procedure VerifySingleGeneratedFile(SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header"; CountErrorMsg: Text)
    var
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
    begin
        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        _Assert.AreEqual(1, SAFTExportLine.Count(), CountErrorMsg);
        SAFTExportLine.SetAutoCalcFields("SAF-T File");
        SAFTExportLine.FindFirst();
        _Assert.AreEqual(SAFTExportLine.Status::Completed, SAFTExportLine.Status, 'The regenerated line must complete.');
        _Assert.IsTrue(SAFTExportLine."SAF-T File".HasValue(), 'The regenerated line must hold the SAF-T file.');
    end;

    local procedure ReadExportedXml(SAFTExportLine: Record "NPR DK SAF-T Cash Export Line"; var Document: XmlDocument; var NamespaceManager: XmlNamespaceManager)
    var
        InStr: InStream;
    begin
        SAFTExportLine.CalcFields("SAF-T File");
        _Assert.IsTrue(SAFTExportLine."SAF-T File".HasValue(), 'The export line must hold the SAF-T file.');
        SAFTExportLine."SAF-T File".CreateInStream(InStr, TextEncoding::UTF8);
        _Assert.IsTrue(XmlDocument.ReadFrom(InStr, Document), 'The SAF-T file must be well-formed XML.');
        NamespaceManager.NameTable(Document.NameTable());
        NamespaceManager.AddNamespace('s', _SAFTNamespaceTxt);
    end;

    local procedure CountNodes(Document: XmlDocument; NamespaceManager: XmlNamespaceManager; XPath: Text): Integer
    var
        Nodes: XmlNodeList;
    begin
        Document.SelectNodes(XPath, NamespaceManager, Nodes);
        exit(Nodes.Count());
    end;

    [ConfirmHandler]
    procedure ConfirmHandler(Question: Text[1024]; var Reply: Boolean)
    var
        ExpectedQuestion: Text;
    begin
        _Assert.AreNotEqual(0, _ExpectedConfirmQuestions.Count(), StrSubstNo('Unexpected confirmation: ''%1''.', Question));
        ExpectedQuestion := _ExpectedConfirmQuestions.Get(1);
        _Assert.IsTrue(StrPos(Question, ExpectedQuestion) > 0, StrSubstNo('Unexpected confirmation. Expected it to contain ''%1'' but got ''%2''.', ExpectedQuestion, Question));
        Reply := _ConfirmReplies.Get(1);
        _ExpectedConfirmQuestions.RemoveAt(1);
        _ConfirmReplies.RemoveAt(1);
    end;
}
