page 6151322 "NPR POSSaleDigitalRcptEntries"
{
    Extensible = false;
    Editable = false;
    Caption = 'POS Sale Digital Receipt Entries';
    PageType = List;
    SourceTable = "NPR POSSale Dig. Receipt Entry";
    SourceTableView = sorting("POS Entry No.")
                      ORDER(Descending);
    UsageCategory = None;

    layout
    {
        area(content)
        {
            repeater(General)
            {
                field(Id; Rec.Id)
                {
                    ApplicationArea = NPRRetail;
                    ToolTip = 'Specifies the unique identifier for the digital receipt entry.';
                }
                field(PDFLink; Rec.PDFLink)
                {
                    ApplicationArea = NPRRetail;
                    ToolTip = 'Specifies the link to the PDF preview of the digital receipt, generated by Fiskaly after the sale.';

                    trigger OnDrillDown()
                    begin
                        Hyperlink(Rec.PDFLink);
                    end;
                }
                field("POS Entry No."; Rec."POS Entry No.")
                {
                    ApplicationArea = NPRRetail;
                    ToolTip = 'Specifies the entry number associated with the POS Entry linked to this digital receipt.';
                }
                field("POS Unit No."; Rec."POS Unit No.")
                {
                    ApplicationArea = NPRRetail;
                    ToolTip = 'Specifies the number assigned to the POS Unit related to this digital receipt.';
                }
                field("Sales Ticket No."; Rec."Sales Ticket No.")
                {
                    ApplicationArea = NPRRetail;
                    ToolTip = 'Specifies the identifier for the sales ticket associated with this digital receipt entry.';
                }
            }
        }
        area(FactBoxes)
        {
            part(DigitalReceiptPDFPreview; "NPR PDF Digital Receipt Viewer")
            {
                SubPageLink = PDFLink = field(PDFLink);
                ApplicationArea = NPRRetail;
            }

        }
    }
}
