trigger: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.18.x"
    displayName: "Install Node.js 12.18.x"

  - script: |
      # Identifying versions
      node --version
      npm --version
      tsc --version
    displayName: "Environment specification"

  - script: |
      cd $(Build.SourcesDirectory)/$(Build.Repository.Name)/packages/dragonglass-core
      npm install pnpm --global

      pnpm multi install
    displayName: "Install dependencies"

  - script: |
      cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
      npm run test-ci
    displayName: "Run tests"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/junit.xml"
      testRunTitle: PR validation test run
    displayName: Publish test results

  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    displayName: Publish code coverage results
  - script: |
      cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
      npm run build
    displayName: "Run build"
