codeunit 85492 "NPR Library SE Journal Schema"
{
    // Official Skatteverket XSD for SKVFS 2021:16 journal export, schema version 2021-12-08:
    // https://www.skatteverket.se/download/18.5dc1d8b31903014b1bf11b9/1719999713439/xml-schema-kassaregister.zip
    // The three component files share one namespace and are joined here into one schema. Annotations are removed.
    // Nothing else is changed.

    procedure InstansNamespace(): Text
    begin
        exit('http://xmls.skatteverket.se/se/skatteverket/td/instans/utredningsstod/1.0');
    end;

    procedure KomponentNamespace(): Text
    begin
        exit('http://xmls.skatteverket.se/se/skatteverket/td/komponent/utredningsstod/1.0');
    end;

    procedure AssertMatchesSchema(Document: XmlDocument)
    var
        Assert: Codeunit Assert;
        Root: XmlElement;
    begin
        // The validator only warns about elements it has no schema for, so a document outside the
        // schema namespace would pass without being checked at all. Pin the root element first.
        Assert.IsTrue(Document.GetRoot(Root), 'The journal has no root element');
        Assert.AreEqual(InstansNamespace(), Root.NamespaceUri(), 'Namespace of the root element');
        Assert.AreEqual('ExportAvDataFranJournalminneEnligtSKVFS2021-16', Root.LocalName(), 'Name of the root element');
        if not TryValidate(Document) then
            Error(GetLastErrorText());
    end;

    local procedure TryValidate(Document: XmlDocument): Boolean
    var
        XmlValidation: Codeunit "Xml Validation";
    begin
        if not XmlValidation.TrySetValidatedDocument(Document) then
            exit(false);
        if not XmlValidation.TryAddValidationSchema(KomponentSchema().ToText(), KomponentNamespace()) then
            exit(false);
        if not XmlValidation.TryAddValidationSchema(InstansSchema().ToText(), InstansNamespace()) then
            exit(false);
        exit(XmlValidation.TryValidateAgainstSchema());
    end;

    local procedure InstansSchema() Schema: TextBuilder
    begin
        Schema.Append('<xs:schema xmlns:utrein="http://xmls.skatteverket.se/se/skatteverket/td/instans/utredningsstod/1.0" xmlns:utreko="http://xmls.skatteverket.se/se/skatteverket/td/komponent/utredningsstod/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmls.skatteverket.se/se/skatteverket/td/instans/utredningsstod/1.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0" xml:lang="sv">');
        Schema.Append('<xs:import namespace="http://xmls.skatteverket.se/se/skatteverket/td/komponent/utredningsstod/1.0" />');
        Schema.Append('<xs:element name="ExportAvDataFranJournalminneEnligtSKVFS2021-16" type="utrein:ExportAvDataFranJournalminneEnligtSKVFS2021-16TYPE"></xs:element>');
        Schema.Append('<xs:complexType name="ExportAvDataFranJournalminneEnligtSKVFS2021-16TYPE"><xs:sequence><xs:element ref="utreko:InloggadAnvandareVidExportAvDataFranJournalminnet" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:BeteckningPaDetKassaregisterSomExportAvDataFranJournalminnetSkerIfran" /><xs:element ref="utreko:TidpunktForNarExportAvDataFranJournalminnetSker" />');
        Schema.Append('<xs:element ref="utreko:ValdPeriodForExportAvDataFranJournalminne" /><xs:element ref="utreko:BeteckningPaValdaKassaregisterForExportAvDataFranJournalminnenLISTA" />');
        Schema.Append('<xs:element ref="utreko:InformationOmForetaget" /><xs:element ref="utreko:KassaregistersystemLISTA" /><xs:element ref="utreko:RegistreringLISTA" /></xs:sequence></xs:complexType>');
        Schema.Append('</xs:schema>');
    end;

    local procedure KomponentSchema() Schema: TextBuilder
    begin
        Schema.Append('<xs:schema xmlns:utreko="http://xmls.skatteverket.se/se/skatteverket/td/komponent/utredningsstod/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmls.skatteverket.se/se/skatteverket/td/komponent/utredningsstod/1.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">');
        Schema.Append('<xs:element name="OrganisationsnummerTEST" type="utreko:OrganisationsnummerTYPE"></xs:element><xs:simpleType name="OrganisationsnummerTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:length value="10" /><xs:pattern value="[\d]{2}[2-9]{1}[\d]{7}" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="PersonnummerMedSekelTEST" type="utreko:PersonnummerMedSekelTYPE"></xs:element><xs:simpleType name="PersonnummerMedSekelTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:length value="12" />');
        Schema.Append('<xs:pattern value="((((19|20)[0-9][0-9])(((01|03|05|07|08|10|12)(0[1-9]|1[0-9]|2[0-9]|3[0-1]))|((04|06|09|11)(0[1-9]|1[0-9]|2[0-9]|30))|((02)(0[1-9]|1[0-9]|2[0-8]))))|(((19|20)(04|08|12|16|20|24|28|32|36|40|44|48|52|56|60|64|68|72|76|80|84|88|92|96)(0229))|(20000229)))(00[1-9]|0[1-9][0-9]|[1-9][0-9][0-9])[0-9]" />');
        Schema.Append('</xs:restriction></xs:simpleType><xs:element name="OrganisationsnummerEllerPersonnummerTEST" type="utreko:OrganisationsnummerEllerPersonnummerTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="OrganisationsnummerEllerPersonnummerTYPE"><xs:union memberTypes="utreko:OrganisationsnummerTYPE utreko:PersonnummerMedSekelTYPE" /></xs:simpleType>');
        Schema.Append('<xs:element name="LopnummerTEST" type="utreko:LopnummerTYPE"></xs:element><xs:simpleType name="LopnummerTYPE"><xs:restriction base="xs:token"><xs:minLength value="1" />');
        Schema.Append('<xs:maxLength value="12" /><xs:pattern value="\d*" /></xs:restriction></xs:simpleType><xs:element name="DatumOchKlockslagTEST" type="utreko:DatumOchKlockslagTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="DatumOchKlockslagTYPE"><xs:restriction base="xs:dateTime"><xs:pattern value="[2]{1}[0]{1}[1-9]{1}[0-9]{1}.{15}" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TillverkningsnummerForKontrollenhetenTEST" type="utreko:TillverkningsnummerForKontrollenhetenTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TillverkningsnummerForKontrollenhetenTYPE"><xs:restriction base="xs:string"><xs:length value="17" /><xs:pattern value="([a-z]|[A-Z]|[0-9]|[ ]|[\-])*" />');
        Schema.Append('</xs:restriction></xs:simpleType><xs:element name="TillverkningsnummerForKontrollsystemetTEST" type="utreko:TillverkningsnummerForKontrollsystemetTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TillverkningsnummerForKontrollsystemetTYPE"><xs:restriction base="xs:string"><xs:length value="17" /><xs:pattern value="([a-z]|[A-Z]|[0-9]|[ ])*" />');
        Schema.Append('</xs:restriction></xs:simpleType><xs:element name="TillverkningsnummerForKassaregistretTEST" type="utreko:TillverkningsnummerForKassaregistretTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TillverkningsnummerForKassaregistretTYPE"><xs:restriction base="xs:string"><xs:maxLength value="48" /><xs:minLength value="1" />');
        Schema.Append('<xs:pattern value="(([0-9]|[a-z]|[A-Z]|[\-]){1})(([0-9]|[a-z]|[A-Z]|[\-]|[ ][0-9]|[ ][a-z]|[ ][A-Z]|[ ][\-])*)(([0-9]|[a-z]|[A-Z]|[\-])?)" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="UtlandskValutaTEST" type="utreko:UtlandskValutaTYPE"></xs:element><xs:simpleType name="UtlandskValutaTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="1" /><xs:maxLength value="72" /><xs:pattern value="([A-Z]|[Å]|[Ä]|[Ö]|[a-z]|[å]|[ä]|[ö])*" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="AntalAvRegistreradArtikel" type="utreko:AntalAvRegistreradArtikelTYPE"></xs:element><xs:simpleType name="AntalAvRegistreradArtikelTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="AntalAvSaldArtikel" type="utreko:AntalAvSaldArtikelTYPE"></xs:element><xs:simpleType name="AntalAvSaldArtikelTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="AntalKassakvitton" type="utreko:AntalKassakvittonTYPE"></xs:element><xs:simpleType name="AntalKassakvittonTYPE"><xs:restriction base="xs:integer">');
        Schema.Append('<xs:minInclusive value="0" /><xs:maxInclusive value="9999999999999" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="AntalKassaladoppningar" type="utreko:AntalKassaladoppningarTYPE"></xs:element><xs:simpleType name="AntalKassaladoppningarTYPE"><xs:restriction base="xs:integer">');
        Schema.Append('<xs:minInclusive value="0" /><xs:maxInclusive value="9999999999999" /></xs:restriction></xs:simpleType><xs:element name="AntalKvittokopior" type="utreko:AntalKvittokopiorTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="AntalKvittokopiorTYPE"><xs:restriction base="xs:integer"><xs:minInclusive value="0" /><xs:maxInclusive value="9999999999999" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="AntalKvittonSomTagitsFramIOvningslage" type="utreko:AntalKvittonSomTagitsFramIOvningslageTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="AntalKvittonSomTagitsFramIOvningslageTYPE"><xs:restriction base="xs:integer"><xs:minInclusive value="0" /><xs:maxInclusive value="9999999999999" />');
        Schema.Append('</xs:restriction></xs:simpleType><xs:element name="AntalOavslutadeForsaljningar" type="utreko:AntalOavslutadeForsaljningarTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="AntalOavslutadeForsaljningarTYPE"><xs:restriction base="xs:integer"><xs:minInclusive value="0" /><xs:maxInclusive value="9999999999999" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="AntalOvrigaRegistreringarSomMinskatDagensForsaljningsbelopp" type="utreko:AntalOvrigaRegistreringarSomMinskatDagensForsaljningsbeloppTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="AntalOvrigaRegistreringarSomMinskatDagensForsaljningsbeloppTYPE"><xs:restriction base="xs:integer"><xs:minInclusive value="0" />');
        Schema.Append('<xs:maxInclusive value="9999999999999" /></xs:restriction></xs:simpleType><xs:element name="AntalReturer" type="utreko:AntalReturerTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="AntalReturerTYPE"><xs:restriction base="xs:integer"><xs:minInclusive value="0" /><xs:maxInclusive value="9999999999999" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="AntalSaldaTjanster" type="utreko:AntalSaldaTjansterTYPE"></xs:element><xs:simpleType name="AntalSaldaTjansterTYPE"><xs:restriction base="xs:decimal">');
        Schema.Append('<xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="AntalSaldaVaror" type="utreko:AntalSaldaVarorTYPE"></xs:element><xs:simpleType name="AntalSaldaVarorTYPE"><xs:restriction base="xs:decimal">');
        Schema.Append('<xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="AnvandaClear" type="utreko:AnvandaClearTYPE"></xs:element><xs:simpleType name="AnvandaClearTYPE"><xs:restriction base="xs:token"><xs:enumeration value="JA">');
        Schema.Append('</xs:enumeration></xs:restriction></xs:simpleType><xs:element name="Artikelnamn" type="utreko:ArtikelnamnTYPE"></xs:element><xs:simpleType name="ArtikelnamnTYPE">');
        Schema.Append('<xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ArtikelnsRegistreringstidpunkt" type="utreko:ArtikelnsRegistreringstidpunktTYPE"></xs:element><xs:simpleType name="ArtikelnsRegistreringstidpunktTYPE">');
        Schema.Append('<xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType><xs:element name="Artikelnummer" type="utreko:ArtikelnummerTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ArtikelnummerTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="Avstamningskod" type="utreko:AvstamningskodTYPE"></xs:element><xs:simpleType name="AvstamningskodTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="113" /><xs:maxLength value="113" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="AvstamningskodForKvittotSomKopianAvser" type="utreko:AvstamningskodForKvittotSomKopianAvserTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="AvstamningskodForKvittotSomKopianAvserTYPE"><xs:restriction base="xs:string"><xs:minLength value="113" /><xs:maxLength value="113" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="BeloppIUtlandskValuta" type="utreko:BeloppIUtlandskValutaTYPE"></xs:element><xs:simpleType name="BeloppIUtlandskValutaTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="BenamningPaRabatt" type="utreko:BenamningPaRabattTYPE"></xs:element><xs:simpleType name="BenamningPaRabattTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType><xs:element name="Betalningsmedel" type="utreko:BetalningsmedelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="BetalningsmedelTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="BeteckningPaDetKassaregisterSomExportAvDataFranJournalminnetSkerIfran" type="utreko:BeteckningPaDetKassaregisterSomExportAvDataFranJournalminnetSkerIfranTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="BeteckningPaDetKassaregisterSomExportAvDataFranJournalminnetSkerIfranTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" />');
        Schema.Append('<xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="BeteckningPaValtKassaregisterForExportAvDataFranJournalminnet" type="utreko:BeteckningPaValtKassaregisterForExportAvDataFranJournalminnetTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="BeteckningPaValtKassaregisterForExportAvDataFranJournalminnetTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" />');
        Schema.Append('</xs:restriction></xs:simpleType><xs:element name="DatumOchKlockslagNarKvittoFramstalls" type="utreko:DatumOchKlockslagNarKvittoFramstallsTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="DatumOchKlockslagNarKvittoFramstallsTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="DatumOchKlockslagNarOriginalkvittoFramstalldes" type="utreko:DatumOchKlockslagNarOriginalkvittoFramstalldesTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="DatumOchKlockslagNarOriginalkvittoFramstalldesTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="DatumOchKlockslagNarProFormaKvittoFramstalls" type="utreko:DatumOchKlockslagNarProFormaKvittoFramstallsTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="DatumOchKlockslagNarProFormaKvittoFramstallsTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="DatumOchKlockslagNarRapportFramstalls" type="utreko:DatumOchKlockslagNarRapportFramstallsTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="DatumOchKlockslagNarRapportFramstallsTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="DatumOchKlockslagNarReturkvittoFramstalls" type="utreko:DatumOchKlockslagNarReturkvittoFramstallsTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="DatumOchKlockslagNarReturkvittoFramstallsTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="DenAdressDarForsaljningSker" type="utreko:DenAdressDarForsaljningSkerTYPE"></xs:element><xs:simpleType name="DenAdressDarForsaljningSkerTYPE">');
        Schema.Append('<xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ElektroniskKopiaAvKassakvitto" type="utreko:ElektroniskKopiaAvKassakvittoTYPE"></xs:element><xs:simpleType name="ElektroniskKopiaAvKassakvittoTYPE">');
        Schema.Append('<xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ElektronisktKassakvitto" type="utreko:ElektronisktKassakvittoTYPE"></xs:element><xs:simpleType name="ElektronisktKassakvittoTYPE"><xs:restriction base="xs:token">');
        Schema.Append('<xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType><xs:element name="EnhetForViktLangdTidEllerVolym" type="utreko:EnhetForViktLangdTidEllerVolymTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="EnhetForViktLangdTidEllerVolymTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="ForandringAvVaxelkassaISvenskaKronor" type="utreko:ForandringAvVaxelkassaISvenskaKronorTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ForandringAvVaxelkassaISvenskaKronorTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="ForetagetsNamn" type="utreko:ForetagetsNamnTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ForetagetsNamnTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ForsaljningssummaPerBetalningsmedel" type="utreko:ForsaljningssummaPerBetalningsmedelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ForsaljningssummaPerBetalningsmedelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="GrandTotalForsaljning" type="utreko:GrandTotalForsaljningTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="GrandTotalForsaljningTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="0" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="GrandTotalNetto" type="utreko:GrandTotalNettoTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="GrandTotalNettoTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="GrandTotalRetur" type="utreko:GrandTotalReturTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="GrandTotalReturTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="IdentitetsbeteckningForRegistreringAvArtiklar" type="utreko:IdentitetsbeteckningForRegistreringAvArtiklarTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="IdentitetsbeteckningForRegistreringAvArtiklarTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="IdentitetsbeteckningForTidigareParkering" type="utreko:IdentitetsbeteckningForTidigareParkeringTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="IdentitetsbeteckningForTidigareParkeringTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="IdentitetsbeteckningPaParkering" type="utreko:IdentitetsbeteckningPaParkeringTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="IdentitetsbeteckningPaParkeringTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="InloggadAnvandare" type="utreko:InloggadAnvandareTYPE"></xs:element><xs:simpleType name="InloggadAnvandareTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="InloggadAnvandareVidExportAvDataFranJournalminnet" type="utreko:InloggadAnvandareVidExportAvDataFranJournalminnetTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="InloggadAnvandareVidExportAvDataFranJournalminnetTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="InloggningIKassaregister" type="utreko:InloggningIKassaregisterTYPE"></xs:element><xs:simpleType name="InloggningIKassaregisterTYPE">');
        Schema.Append('<xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType><xs:element name="Kassabeteckning" type="utreko:KassabeteckningTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="KassabeteckningTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="Kontrollkod" type="utreko:KontrollkodTYPE"></xs:element><xs:simpleType name="KontrollkodTYPE"><xs:restriction base="xs:string"><xs:minLength value="59" />');
        Schema.Append('<xs:maxLength value="59" /></xs:restriction></xs:simpleType><xs:element name="KontrollkodForKvittotSomKopianAvser" type="utreko:KontrollkodForKvittotSomKopianAvserTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="KontrollkodForKvittotSomKopianAvserTYPE"><xs:restriction base="xs:string"><xs:minLength value="59" /><xs:maxLength value="59" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="KontrollkodPaKopiaAvKassakvitto" type="utreko:KontrollkodPaKopiaAvKassakvittoTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="KontrollkodPaKopiaAvKassakvittoTYPE"><xs:restriction base="xs:string"><xs:minLength value="59" /><xs:maxLength value="59" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="LopnummerForKassakvitto" type="utreko:LopnummerTYPE"></xs:element><xs:element name="LopnummerForKvittokopia" type="utreko:LopnummerTYPE"></xs:element>');
        Schema.Append('<xs:element name="LopnummerForOvningskvitto" type="utreko:LopnummerForOvningskvittoTYPE"></xs:element><xs:simpleType name="LopnummerForOvningskvittoTYPE">');
        Schema.Append('<xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="12" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="LopnummerForUrsprungligtKassakvitto" type="utreko:LopnummerTYPE"></xs:element><xs:element name="LopnummerForZDagrapport" type="utreko:LopnummerTYPE"></xs:element>');
        Schema.Append('<xs:element name="LopnummerForZDagrapportPaKvitto" type="utreko:LopnummerTYPE"></xs:element><xs:element name="LopnummerPaOriginalkvitto" type="utreko:LopnummerTYPE"></xs:element>');
        Schema.Append('<xs:element name="MangdAvRegistreradArtikel" type="utreko:MangdAvRegistreradArtikelTYPE"></xs:element><xs:simpleType name="MangdAvRegistreradArtikelTYPE">');
        Schema.Append('<xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="MangdAvSaldArtikel" type="utreko:MangdAvSaldArtikelTYPE"></xs:element><xs:simpleType name="MangdAvSaldArtikelTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="MervardesskattPaForsaljningsbeloppet" type="utreko:MervardesskattPaForsaljningsbeloppetTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="MervardesskattPaForsaljningsbeloppetTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="MervardesskattPaRegistreradArtikel" type="utreko:MervardesskattPaRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="MervardesskattPaRegistreradArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="MervardesskattPaSaldArtikel" type="utreko:MervardesskattPaSaldArtikelTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="MervardesskattPaSaldArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="Mervardesskattesats" type="utreko:MervardesskattesatsTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="MervardesskattesatsTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="0" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="MervardesskattesatsForRegistreradArtikel" type="utreko:MervardesskattesatsForRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="MervardesskattesatsForRegistreradArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="MervardesskattesatsForSaldArtikel" type="utreko:MervardesskattesatsForSaldArtikelTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="MervardesskattesatsForSaldArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ModellEllerProgramForKassaregistret" type="utreko:ModellEllerProgramForKassaregistretTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ModellEllerProgramForKassaregistretTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="ModellbeteckningForKassaregistret" type="utreko:ModellbeteckningForKassaregistretTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ModellbeteckningForKassaregistretTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="NamnPaHuvudgrupp" type="utreko:NamnPaHuvudgruppTYPE"></xs:element><xs:simpleType name="NamnPaHuvudgruppTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType><xs:element name="NamnPaOvrigRapport" type="utreko:NamnPaOvrigRapportTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="NamnPaOvrigRapportTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="NamnPaVerksamheten" type="utreko:NamnPaVerksamhetenTYPE"></xs:element><xs:simpleType name="NamnPaVerksamhetenTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="NyTidVidOmstallningAvKlockan" type="utreko:NyTidVidOmstallningAvKlockanTYPE"></xs:element><xs:simpleType name="NyTidVidOmstallningAvKlockanTYPE">');
        Schema.Append('<xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType><xs:element name="OmstartAvKassaregister" type="utreko:OmstartAvKassaregisterTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="OmstartAvKassaregisterTYPE"><xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="OppnaKassaladaVidNollforsaljning" type="utreko:OppnaKassaladaVidNollforsaljningTYPE"></xs:element><xs:simpleType name="OppnaKassaladaVidNollforsaljningTYPE">');
        Schema.Append('<xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="OrganisationsnummerEllerPersonnummer" type="utreko:OrganisationsnummerEllerPersonnummerTYPE"></xs:element>');
        Schema.Append('<xs:element name="OriginalkvittoUtskrivetUtanKontaktMedKontrollservern" type="utreko:OriginalkvittoUtskrivetUtanKontaktMedKontrollservernTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="OriginalkvittoUtskrivetUtanKontaktMedKontrollservernTYPE"><xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="OrsakTillAndring" type="utreko:OrsakTillAndringTYPE"></xs:element><xs:simpleType name="OrsakTillAndringTYPE"><xs:restriction base="xs:string">');
        Schema.Append('<xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType><xs:element name="PrisPaEfterfragadArtikel" type="utreko:PrisPaEfterfragadArtikelTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="PrisPaEfterfragadArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="PrisPaRegistreradArtikel" type="utreko:PrisPaRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="PrisPaRegistreradArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="PrisPaSaldArtikel" type="utreko:PrisPaSaldArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="PrisPaSaldArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="PrisPerEnhet" type="utreko:PrisPerEnhetTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="PrisPerEnhetTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="RabattensBelopp" type="utreko:RabattensBeloppTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="RabattensBeloppTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="RabattensBeloppPaKvittoniva" type="utreko:RabattensBeloppPaKvittonivaTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="RabattensBeloppPaKvittonivaTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="RabatternasBelopp" type="utreko:RabatternasBeloppTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="RabatternasBeloppTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="Registreringstidpunkt" type="utreko:RegistreringstidpunktTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="RegistreringstidpunktTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ReturernasBelopp" type="utreko:ReturernasBeloppTYPE"></xs:element><xs:simpleType name="ReturernasBeloppTYPE"><xs:restriction base="xs:decimal">');
        Schema.Append('<xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="Sokparameter" type="utreko:SokparameterTYPE"></xs:element><xs:simpleType name="SokparameterTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" />');
        Schema.Append('<xs:maxLength value="256" /></xs:restriction></xs:simpleType><xs:element name="StallaOmTillNormallage" type="utreko:StallaOmTillNormallageTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="StallaOmTillNormallageTYPE"><xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="StallaOmTillOvningslage" type="utreko:StallaOmTillOvningslageTYPE"></xs:element><xs:simpleType name="StallaOmTillOvningslageTYPE"><xs:restriction base="xs:token">');
        Schema.Append('<xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType><xs:element name="StartAvKassaregister" type="utreko:StartAvKassaregisterTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="StartAvKassaregisterTYPE"><xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="StatuskodFranKontrollprogrammet" type="utreko:StatuskodFranKontrollprogrammetTYPE"></xs:element><xs:simpleType name="StatuskodFranKontrollprogrammetTYPE">');
        Schema.Append('<xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="StoppAvKassaregister" type="utreko:StoppAvKassaregisterTYPE"></xs:element><xs:simpleType name="StoppAvKassaregisterTYPE"><xs:restriction base="xs:token">');
        Schema.Append('<xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TidigareAntalAvRegistreradArtikel" type="utreko:TidigareAntalAvRegistreradArtikelTYPE"></xs:element><xs:simpleType name="TidigareAntalAvRegistreradArtikelTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="TidigareBeloppPaRabatten" type="utreko:TidigareBeloppPaRabattenTYPE"></xs:element><xs:simpleType name="TidigareBeloppPaRabattenTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="TidigareBenamningPaRabatt" type="utreko:TidigareBenamningPaRabattTYPE"></xs:element><xs:simpleType name="TidigareBenamningPaRabattTYPE">');
        Schema.Append('<xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TidigareEnhetForViktLangdTidEllerVolym" type="utreko:TidigareEnhetForViktLangdTidEllerVolymTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TidigareEnhetForViktLangdTidEllerVolymTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="TidigareMangdAvRegistreradArtikel" type="utreko:TidigareMangdAvRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TidigareMangdAvRegistreradArtikelTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TidigareMervardesskattPaRegistreradArtikel" type="utreko:TidigareMervardesskattPaRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TidigareMervardesskattPaRegistreradArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TidigareMervardesskattesatsForRegistreradArtikel" type="utreko:TidigareMervardesskattesatsForRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TidigareMervardesskattesatsForRegistreradArtikelTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" />');
        Schema.Append('<xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TidigarePrisPaRegistreradArtikel" type="utreko:TidigarePrisPaRegistreradArtikelTYPE"></xs:element><xs:simpleType name="TidigarePrisPaRegistreradArtikelTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="TidigarePrisPerEnhet" type="utreko:TidigarePrisPerEnhetTYPE"></xs:element><xs:simpleType name="TidigarePrisPerEnhetTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="TidpunktForNarExportAvDataFranJournalminnetSker" type="utreko:TidpunktForNarExportAvDataFranJournalminnetSkerTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TidpunktForNarExportAvDataFranJournalminnetSkerTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TillverkningsnummerForKassaregistret" type="utreko:TillverkningsnummerForKassaregistretTYPE"></xs:element>');
        Schema.Append('<xs:element name="TillverkningsnummerForKontrollenheten" type="utreko:TillverkningsnummerForKontrollenhetenTYPE"></xs:element>');
        Schema.Append('<xs:element name="TillverkningsnummerForKontrollsystemet" type="utreko:TillverkningsnummerForKontrollsystemetTYPE"></xs:element>');
        Schema.Append('<xs:element name="TotalForsaljningssumma" type="utreko:TotalForsaljningssummaTYPE"></xs:element><xs:simpleType name="TotalForsaljningssummaTYPE"><xs:restriction base="xs:decimal">');
        Schema.Append('<xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TotalForsaljningssummaForHuvudgrupp" type="utreko:TotalForsaljningssummaForHuvudgruppTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TotalForsaljningssummaForHuvudgruppTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TotaltBeloppAvOavslutadeForsaljningar" type="utreko:TotaltBeloppAvOavslutadeForsaljningarTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TotaltBeloppAvOavslutadeForsaljningarTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="0" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TotaltBeloppAvOvrigaRegistreringarSomMinskatDagensForsaljningsbelopp" type="utreko:TotaltBeloppAvOvrigaRegistreringarSomMinskatDagensForsaljningsbeloppTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="TotaltBeloppAvOvrigaRegistreringarSomMinskatDagensForsaljningsbeloppTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" />');
        Schema.Append('<xs:minInclusive value="0" /><xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TotaltBeloppIOvningslage" type="utreko:TotaltBeloppIOvningslageTYPE"></xs:element><xs:simpleType name="TotaltBeloppIOvningslageTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="0" /><xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TotaltBeloppPaKvittokopior" type="utreko:TotaltBeloppPaKvittokopiorTYPE"></xs:element><xs:simpleType name="TotaltBeloppPaKvittokopiorTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="TotaltForsaljningsbeloppISvenskaKronor" type="utreko:TotaltForsaljningsbeloppISvenskaKronorTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TotaltForsaljningsbeloppISvenskaKronorTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="TotaltMervardesskattebeloppPerSkattesats" type="utreko:TotaltMervardesskattebeloppPerSkattesatsTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TotaltMervardesskattebeloppPerSkattesatsTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="TotaltRabattbeloppPaKvitto" type="utreko:TotaltRabattbeloppPaKvittoTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TotaltRabattbeloppPaKvittoTYPE"><xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" />');
        Schema.Append('<xs:maxInclusive value="99999999999.99" /></xs:restriction></xs:simpleType><xs:element name="TypAvArtikel" type="utreko:TypAvArtikelTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="TypAvArtikelTYPE"><xs:restriction base="xs:token"><xs:enumeration value="VARA"></xs:enumeration><xs:enumeration value="TJANST"></xs:enumeration>');
        Schema.Append('</xs:restriction></xs:simpleType><xs:element name="TypAvRadering" type="utreko:TypAvRaderingTYPE"></xs:element><xs:simpleType name="TypAvRaderingTYPE">');
        Schema.Append('<xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="UrsprungligRegistreringstidpunkt" type="utreko:UrsprungligRegistreringstidpunktTYPE"></xs:element><xs:simpleType name="UrsprungligRegistreringstidpunktTYPE">');
        Schema.Append('<xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType><xs:element name="UtlandskValuta" type="utreko:UtlandskValutaTYPE"></xs:element>');
        Schema.Append('<xs:element name="UtloggningUrKassaregister" type="utreko:UtloggningUrKassaregisterTYPE"></xs:element><xs:simpleType name="UtloggningUrKassaregisterTYPE">');
        Schema.Append('<xs:restriction base="xs:token"><xs:enumeration value="JA"></xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="UtskriftAvKvittoUtanAttKontrollprogrammetHarKontaktMedKontrollservern" type="utreko:UtskriftAvKvittoUtanAttKontrollprogrammetHarKontaktMedKontrollservernTYPE">');
        Schema.Append('</xs:element><xs:simpleType name="UtskriftAvKvittoUtanAttKontrollprogrammetHarKontaktMedKontrollservernTYPE"><xs:restriction base="xs:token"><xs:enumeration value="JA">');
        Schema.Append('</xs:enumeration></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ValdSluttidpunktForExportAvDataFranJournalminnet" type="utreko:ValdSluttidpunktForExportAvDataFranJournalminnetTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ValdSluttidpunktForExportAvDataFranJournalminnetTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="ValdStarttidpunktForExportAvDataFranJournalminnet" type="utreko:ValdStarttidpunktForExportAvDataFranJournalminnetTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="ValdStarttidpunktForExportAvDataFranJournalminnetTYPE"><xs:restriction base="utreko:DatumOchKlockslagTYPE"></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="VaxelkassansBeloppISvenskaKronor" type="utreko:VaxelkassansBeloppISvenskaKronorTYPE"></xs:element><xs:simpleType name="VaxelkassansBeloppISvenskaKronorTYPE">');
        Schema.Append('<xs:restriction base="xs:decimal"><xs:fractionDigits value="2" /><xs:minInclusive value="-9999999999.99" /><xs:maxInclusive value="99999999999.99" /></xs:restriction>');
        Schema.Append('</xs:simpleType><xs:element name="VersionsnummerForKassaregistret" type="utreko:VersionsnummerForKassaregistretTYPE"></xs:element>');
        Schema.Append('<xs:simpleType name="VersionsnummerForKassaregistretTYPE"><xs:restriction base="xs:string"><xs:minLength value="1" /><xs:maxLength value="72" /></xs:restriction></xs:simpleType>');
        Schema.Append('<xs:element name="AndraParkeradArtikel" type="utreko:AndraParkeradArtikelTYPE"></xs:element><xs:complexType name="AndraParkeradArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" /><xs:element ref="utreko:TypAvArtikel" />');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:AntalAvRegistreradArtikel" /><xs:element ref="utreko:MangdAvRegistreradArtikel" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" /><xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:TidigareAntalAvRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:TidigareMangdAvRegistreradArtikel" minOccurs="0" /><xs:element ref="utreko:TidigareEnhetForViktLangdTidEllerVolym" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TidigarePrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:TidigarePrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:TidigareRabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:TidigareMervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:TidigareMervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:UrsprungligRegistreringstidpunkt" /><xs:element ref="utreko:OrsakTillAndring" minOccurs="0" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="AndraRegistreradArtikel" type="utreko:AndraRegistreradArtikelTYPE"></xs:element><xs:complexType name="AndraRegistreradArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" /><xs:element ref="utreko:TypAvArtikel" />');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:AntalAvRegistreradArtikel" /><xs:element ref="utreko:MangdAvRegistreradArtikel" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" /><xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:TidigareAntalAvRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:TidigareMangdAvRegistreradArtikel" minOccurs="0" /><xs:element ref="utreko:TidigareEnhetForViktLangdTidEllerVolym" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TidigarePrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:TidigarePrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:TidigareRabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:TidigareMervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:TidigareMervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:UrsprungligRegistreringstidpunkt" />');
        Schema.Append('<xs:element ref="utreko:OrsakTillAndring" minOccurs="0" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="BeteckningPaValdaKassaregisterForExportAvDataFranJournalminnenLISTA" type="utreko:BeteckningPaValdaKassaregisterForExportAvDataFranJournalminnenLISTATYPE">');
        Schema.Append('</xs:element><xs:complexType name="BeteckningPaValdaKassaregisterForExportAvDataFranJournalminnenLISTATYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:BeteckningPaValtKassaregisterForExportAvDataFranJournalminnet" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="FlyttaParkeradArtikel" type="utreko:FlyttaParkeradArtikelTYPE"></xs:element><xs:complexType name="FlyttaParkeradArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" /><xs:element ref="utreko:TypAvArtikel" />');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:AntalAvRegistreradArtikel" /><xs:element ref="utreko:MangdAvRegistreradArtikel" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" /><xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForTidigareParkering" minOccurs="0" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="ForandraVaxelkassa" type="utreko:ForandraVaxelkassaTYPE"></xs:element><xs:complexType name="ForandraVaxelkassaTYPE"><xs:sequence><xs:choice>');
        Schema.Append('<xs:element ref="utreko:ForandringAvVaxelkassaISvenskaKronor" /><xs:element ref="utreko:ForandringAvVaxelkassaIUtlandskValuta" /></xs:choice></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="ForandringAvVaxelkassaIUtlandskValuta" type="utreko:ForandringAvVaxelkassaIUtlandskValutaTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="ForandringAvVaxelkassaIUtlandskValutaTYPE"><xs:sequence><xs:element ref="utreko:UtlandskValuta" /><xs:element ref="utreko:BeloppIUtlandskValuta" />');
        Schema.Append('</xs:sequence></xs:complexType><xs:element name="Handelse" type="utreko:HandelseTYPE"></xs:element><xs:complexType name="HandelseTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:InloggadAnvandare" minOccurs="0" /><xs:element ref="utreko:Kassabeteckning" /><xs:element ref="utreko:Registreringstidpunkt" /><xs:choice>');
        Schema.Append('<xs:element ref="utreko:RegistreraArtikel" /><xs:element ref="utreko:AndraRegistreradArtikel" /><xs:element ref="utreko:RaderaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:ParkeraRegistreradArtikel" /><xs:element ref="utreko:OppnaParkering" /><xs:element ref="utreko:RaderaParkeradArtikel" />');
        Schema.Append('<xs:element ref="utreko:AndraParkeradArtikel" /><xs:element ref="utreko:FlyttaParkeradArtikel" /><xs:element ref="utreko:StangaParkering" />');
        Schema.Append('<xs:element ref="utreko:OppnaKassaladaVidNollforsaljning" /><xs:element ref="utreko:AnvandaClear" /><xs:element ref="utreko:StallaPrisforfragan" />');
        Schema.Append('<xs:element ref="utreko:ForandraVaxelkassa" /><xs:element ref="utreko:Kassakvitto" /><xs:element ref="utreko:Returkvitto" /><xs:element ref="utreko:KopiaAvKassakvitto" />');
        Schema.Append('<xs:element ref="utreko:ProFormaKvitto" /><xs:element ref="utreko:Ovningskvitto" /><xs:element ref="utreko:XDagrapport" /><xs:element ref="utreko:ZDagrapport" />');
        Schema.Append('<xs:element ref="utreko:OvrigRapport" /><xs:element ref="utreko:StartAvKassaregister" /><xs:element ref="utreko:StoppAvKassaregister" />');
        Schema.Append('<xs:element ref="utreko:OmstartAvKassaregister" /><xs:element ref="utreko:InloggningIKassaregister" /><xs:element ref="utreko:UtloggningUrKassaregister" />');
        Schema.Append('<xs:element ref="utreko:StallaOmKlockan" /><xs:element ref="utreko:StallaOmTillOvningslage" /><xs:element ref="utreko:StallaOmTillNormallage" />');
        Schema.Append('<xs:element ref="utreko:StatuskodFranKontrollprogrammet" /><xs:element ref="utreko:VerifieringAvKvittodataMellanKontrollprogramOchKontrollserver" /></xs:choice></xs:sequence>');
        Schema.Append('</xs:complexType><xs:element name="InformationOmForetaget" type="utreko:InformationOmForetagetTYPE"></xs:element><xs:complexType name="InformationOmForetagetTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" /><xs:element ref="utreko:ForetagetsNamn" /><xs:element ref="utreko:NamnPaVerksamheten" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:DenAdressDarForsaljningSker" /></xs:sequence></xs:complexType><xs:element name="Kassakvitto" type="utreko:KassakvittoTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="KassakvittoTYPE"><xs:sequence><xs:element ref="utreko:ForetagetsNamn" /><xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" />');
        Schema.Append('<xs:element ref="utreko:DenAdressDarForsaljningSker" /><xs:element ref="utreko:DatumOchKlockslagNarKvittoFramstalls" /><xs:element ref="utreko:LopnummerForKassakvitto" />');
        Schema.Append('<xs:element ref="utreko:Kassabeteckning" /><xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" /><xs:element ref="utreko:SaldaArtiklarLISTA" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaKvittonivaLISTA" minOccurs="0" /><xs:element ref="utreko:TotaltRabattbeloppPaKvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltForsaljningsbeloppISvenskaKronor" /><xs:element ref="utreko:TotalaForsaljningsbeloppIUtlandskValutaLISTA" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaForsaljningsbeloppet" /><xs:element ref="utreko:TotalaForsaljningssummorPerBetalningsmedelLISTA" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaOlikaSkattesatserLISTA" /><xs:element ref="utreko:ElektronisktKassakvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:LopnummerForZDagrapportPaKvitto" /><xs:choice><xs:element ref="utreko:TillverkningsnummerForKontrollenheten" />');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKontrollsystemet" /></xs:choice><xs:choice><xs:element ref="utreko:Kontrollkod" /><xs:element ref="utreko:Avstamningskod" />');
        Schema.Append('<xs:element ref="utreko:UtskriftAvKvittoUtanAttKontrollprogrammetHarKontaktMedKontrollservern" /></xs:choice></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="KassaregistersystemLISTA" type="utreko:KassaregistersystemLISTATYPE"></xs:element><xs:complexType name="KassaregistersystemLISTATYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:Kassaregistersystemet" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="Kassaregistersystemet" type="utreko:KassaregistersystemetTYPE"></xs:element><xs:complexType name="KassaregistersystemetTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKassaregistret" /><xs:element ref="utreko:ModellbeteckningForKassaregistret" />');
        Schema.Append('<xs:element ref="utreko:ModellEllerProgramForKassaregistret" /><xs:element ref="utreko:VersionsnummerForKassaregistret" /><xs:element ref="utreko:Kassabeteckning" /><xs:choice>');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKontrollenheten" /><xs:element ref="utreko:TillverkningsnummerForKontrollsystemet" /></xs:choice></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="KopiaAvKassakvitto" type="utreko:KopiaAvKassakvittoTYPE"></xs:element><xs:complexType name="KopiaAvKassakvittoTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:ForetagetsNamn" /><xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" /><xs:element ref="utreko:DenAdressDarForsaljningSker" />');
        Schema.Append('<xs:element ref="utreko:DatumOchKlockslagNarKvittoFramstalls" /><xs:element ref="utreko:DatumOchKlockslagNarOriginalkvittoFramstalldes" />');
        Schema.Append('<xs:element ref="utreko:LopnummerForKvittokopia" /><xs:element ref="utreko:LopnummerPaOriginalkvitto" /><xs:element ref="utreko:Kassabeteckning" />');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" /><xs:element ref="utreko:SaldaArtiklarLISTA" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaKvittonivaLISTA" minOccurs="0" /><xs:element ref="utreko:TotaltRabattbeloppPaKvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltForsaljningsbeloppISvenskaKronor" /><xs:element ref="utreko:TotalaForsaljningsbeloppIUtlandskValutaLISTA" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaForsaljningsbeloppet" /><xs:element ref="utreko:TotalaForsaljningssummorPerBetalningsmedelLISTA" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaOlikaSkattesatserLISTA" /><xs:element ref="utreko:KontrollkodPaKopiaAvKassakvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:ElektroniskKopiaAvKassakvitto" minOccurs="0" /><xs:element ref="utreko:LopnummerForZDagrapportPaKvitto" /><xs:choice>');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKontrollenheten" /><xs:element ref="utreko:TillverkningsnummerForKontrollsystemet" /></xs:choice><xs:choice>');
        Schema.Append('<xs:element ref="utreko:KontrollkodForKvittotSomKopianAvser" /><xs:element ref="utreko:AvstamningskodForKvittotSomKopianAvser" />');
        Schema.Append('<xs:element ref="utreko:OriginalkvittoUtskrivetUtanKontaktMedKontrollservern" /></xs:choice></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="MervardesskattPaOlikaSkattesatserLISTA" type="utreko:MervardesskattPaOlikaSkattesatserLISTATYPE"></xs:element>');
        Schema.Append('<xs:complexType name="MervardesskattPaOlikaSkattesatserLISTATYPE"><xs:sequence><xs:element ref="utreko:MervardesskattPerSkattesats" maxOccurs="unbounded" /></xs:sequence>');
        Schema.Append('</xs:complexType><xs:element name="MervardesskattPerSkattesats" type="utreko:MervardesskattPerSkattesatsTYPE"></xs:element><xs:complexType name="MervardesskattPerSkattesatsTYPE">');
        Schema.Append('<xs:sequence><xs:element ref="utreko:Mervardesskattesats" /><xs:element ref="utreko:TotaltMervardesskattebeloppPerSkattesats" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="OppnaParkering" type="utreko:OppnaParkeringTYPE"></xs:element><xs:complexType name="OppnaParkeringTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" /></xs:sequence></xs:complexType><xs:element name="Ovningskvitto" type="utreko:OvningskvittoTYPE">');
        Schema.Append('</xs:element><xs:complexType name="OvningskvittoTYPE"><xs:sequence><xs:element ref="utreko:ForetagetsNamn" /><xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" />');
        Schema.Append('<xs:element ref="utreko:DenAdressDarForsaljningSker" /><xs:element ref="utreko:DatumOchKlockslagNarKvittoFramstalls" />');
        Schema.Append('<xs:element ref="utreko:LopnummerForOvningskvitto" minOccurs="0" /><xs:element ref="utreko:Kassabeteckning" />');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" /><xs:element ref="utreko:SaldaArtiklarLISTA" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaKvittonivaLISTA" minOccurs="0" /><xs:element ref="utreko:TotaltRabattbeloppPaKvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltForsaljningsbeloppISvenskaKronor" /><xs:element ref="utreko:TotalaForsaljningsbeloppIUtlandskValutaLISTA" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaForsaljningsbeloppet" /><xs:element ref="utreko:TotalaForsaljningssummorPerBetalningsmedelLISTA" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaOlikaSkattesatserLISTA" /><xs:element ref="utreko:LopnummerForZDagrapportPaKvitto" /><xs:choice>');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKontrollenheten" /><xs:element ref="utreko:TillverkningsnummerForKontrollsystemet" /></xs:choice></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="OvrigRapport" type="utreko:OvrigRapportTYPE"></xs:element><xs:complexType name="OvrigRapportTYPE"><xs:sequence><xs:element ref="utreko:NamnPaOvrigRapport" />');
        Schema.Append('<xs:element ref="utreko:Sokparameter" /></xs:sequence></xs:complexType><xs:element name="ParkeraRegistreradArtikel" type="utreko:ParkeraRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="ParkeraRegistreradArtikelTYPE"><xs:sequence><xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TypAvArtikel" /><xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:Artikelnamn" /><xs:element ref="utreko:AntalAvRegistreradArtikel" /><xs:element ref="utreko:MangdAvRegistreradArtikel" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" /><xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="ProFormaKvitto" type="utreko:ProFormaKvittoTYPE"></xs:element><xs:complexType name="ProFormaKvittoTYPE"><xs:sequence><xs:element ref="utreko:ForetagetsNamn" />');
        Schema.Append('<xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" /><xs:element ref="utreko:DenAdressDarForsaljningSker" />');
        Schema.Append('<xs:element ref="utreko:DatumOchKlockslagNarProFormaKvittoFramstalls" /><xs:element ref="utreko:Kassabeteckning" />');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" /><xs:element ref="utreko:SaldaArtiklarLISTA" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaKvittonivaLISTA" minOccurs="0" /><xs:element ref="utreko:TotaltRabattbeloppPaKvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltForsaljningsbeloppISvenskaKronor" /><xs:element ref="utreko:MervardesskattPaForsaljningsbeloppet" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaOlikaSkattesatserLISTA" /><xs:choice><xs:element ref="utreko:TillverkningsnummerForKontrollenheten" />');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKontrollsystemet" /></xs:choice></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RabattPaKvittoniva" type="utreko:RabattPaKvittonivaTYPE"></xs:element><xs:complexType name="RabattPaKvittonivaTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:BenamningPaRabatt" minOccurs="0" /><xs:element ref="utreko:RabattensBeloppPaKvittoniva" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RabattPaRegistreradArtikel" type="utreko:RabattPaRegistreradArtikelTYPE"></xs:element><xs:complexType name="RabattPaRegistreradArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:BenamningPaRabatt" minOccurs="0" /><xs:element ref="utreko:RabattensBelopp" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RabattPaSaldArtikel" type="utreko:RabattPaSaldArtikelTYPE"></xs:element><xs:complexType name="RabattPaSaldArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:BenamningPaRabatt" minOccurs="0" /><xs:element ref="utreko:RabattensBelopp" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RabatterPaKvittonivaLISTA" type="utreko:RabatterPaKvittonivaLISTATYPE"></xs:element><xs:complexType name="RabatterPaKvittonivaLISTATYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:RabattPaKvittoniva" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RabatterPaRegistreradArtikelLISTA" type="utreko:RabatterPaRegistreradArtikelLISTATYPE"></xs:element><xs:complexType name="RabatterPaRegistreradArtikelLISTATYPE">');
        Schema.Append('<xs:sequence><xs:element ref="utreko:RabattPaRegistreradArtikel" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RabatterPaSaldArtikelLISTA" type="utreko:RabatterPaSaldArtikelLISTATYPE"></xs:element><xs:complexType name="RabatterPaSaldArtikelLISTATYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:RabattPaSaldArtikel" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RaderaParkeradArtikel" type="utreko:RaderaParkeradArtikelTYPE"></xs:element><xs:complexType name="RaderaParkeradArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" /><xs:element ref="utreko:TypAvArtikel" />');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:AntalAvRegistreradArtikel" /><xs:element ref="utreko:MangdAvRegistreradArtikel" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" /><xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:UrsprungligRegistreringstidpunkt" /><xs:element ref="utreko:TypAvRadering" minOccurs="0" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="RaderaRegistreradArtikel" type="utreko:RaderaRegistreradArtikelTYPE"></xs:element><xs:complexType name="RaderaRegistreradArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" /><xs:element ref="utreko:TypAvArtikel" />');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:AntalAvRegistreradArtikel" /><xs:element ref="utreko:MangdAvRegistreradArtikel" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" /><xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaRegistreradArtikel" /><xs:element ref="utreko:UrsprungligRegistreringstidpunkt" /><xs:element ref="utreko:TypAvRadering" minOccurs="0" />');
        Schema.Append('</xs:sequence></xs:complexType><xs:element name="RegistreraArtikel" type="utreko:RegistreraArtikelTYPE"></xs:element><xs:complexType name="RegistreraArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" /><xs:element ref="utreko:TypAvArtikel" />');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:AntalAvRegistreradArtikel" /><xs:element ref="utreko:MangdAvRegistreradArtikel" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" /><xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaRegistreradArtikelLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattesatsForRegistreradArtikel" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaRegistreradArtikel" /></xs:sequence></xs:complexType><xs:element name="RegistreringLISTA" type="utreko:RegistreringLISTATYPE"></xs:element>');
        Schema.Append('<xs:complexType name="RegistreringLISTATYPE"><xs:sequence><xs:element ref="utreko:Handelse" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="Returkvitto" type="utreko:ReturkvittoTYPE"></xs:element><xs:complexType name="ReturkvittoTYPE"><xs:sequence><xs:element ref="utreko:ForetagetsNamn" />');
        Schema.Append('<xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" /><xs:element ref="utreko:DenAdressDarForsaljningSker" />');
        Schema.Append('<xs:element ref="utreko:DatumOchKlockslagNarReturkvittoFramstalls" /><xs:element ref="utreko:LopnummerForKassakvitto" />');
        Schema.Append('<xs:element ref="utreko:LopnummerForUrsprungligtKassakvitto" minOccurs="0" /><xs:element ref="utreko:Kassabeteckning" /><xs:element ref="utreko:SaldaArtiklarLISTA" />');
        Schema.Append('<xs:element ref="utreko:RabatterPaKvittonivaLISTA" minOccurs="0" /><xs:element ref="utreko:TotaltRabattbeloppPaKvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltForsaljningsbeloppISvenskaKronor" /><xs:element ref="utreko:TotalaForsaljningsbeloppIUtlandskValutaLISTA" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaForsaljningsbeloppet" /><xs:element ref="utreko:TotalaForsaljningssummorPerBetalningsmedelLISTA" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattPaOlikaSkattesatserLISTA" /><xs:element ref="utreko:ElektronisktKassakvitto" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:LopnummerForZDagrapportPaKvitto" /><xs:choice><xs:element ref="utreko:TillverkningsnummerForKontrollenheten" />');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKontrollsystemet" /></xs:choice><xs:choice><xs:element ref="utreko:Kontrollkod" /><xs:element ref="utreko:Avstamningskod" />');
        Schema.Append('<xs:element ref="utreko:UtskriftAvKvittoUtanAttKontrollprogrammetHarKontaktMedKontrollservern" /></xs:choice></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="SaldArtikel" type="utreko:SaldArtikelTYPE"></xs:element><xs:complexType name="SaldArtikelTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:IdentitetsbeteckningForRegistreringAvArtiklar" minOccurs="0" /><xs:element ref="utreko:TypAvArtikel" />');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:AntalAvSaldArtikel" /><xs:element ref="utreko:MangdAvSaldArtikel" minOccurs="0" /><xs:element ref="utreko:EnhetForViktLangdTidEllerVolym" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:PrisPerEnhet" minOccurs="0" /><xs:element ref="utreko:PrisPaSaldArtikel" /><xs:element ref="utreko:RabatterPaSaldArtikelLISTA" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:MervardesskattesatsForSaldArtikel" /><xs:element ref="utreko:MervardesskattPaSaldArtikel" /><xs:element ref="utreko:ArtikelnsRegistreringstidpunkt" />');
        Schema.Append('</xs:sequence></xs:complexType><xs:element name="SaldaArtiklarLISTA" type="utreko:SaldaArtiklarLISTATYPE"></xs:element><xs:complexType name="SaldaArtiklarLISTATYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:SaldArtikel" maxOccurs="unbounded" /></xs:sequence></xs:complexType><xs:element name="StallaOmKlockan" type="utreko:StallaOmKlockanTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="StallaOmKlockanTYPE"><xs:sequence><xs:element ref="utreko:NyTidVidOmstallningAvKlockan" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="StallaPrisforfragan" type="utreko:StallaPrisforfraganTYPE"></xs:element><xs:complexType name="StallaPrisforfraganTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" /><xs:element ref="utreko:Artikelnummer" minOccurs="0" /><xs:element ref="utreko:Artikelnamn" />');
        Schema.Append('<xs:element ref="utreko:PrisPaEfterfragadArtikel" /></xs:sequence></xs:complexType><xs:element name="StangaParkering" type="utreko:StangaParkeringTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="StangaParkeringTYPE"><xs:sequence><xs:element ref="utreko:IdentitetsbeteckningPaParkering" minOccurs="0" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="TidigareRabattPaRegistreradArtikel" type="utreko:TidigareRabattPaRegistreradArtikelTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="TidigareRabattPaRegistreradArtikelTYPE"><xs:sequence><xs:element ref="utreko:TidigareBenamningPaRabatt" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TidigareBeloppPaRabatten" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="TidigareRabatterPaRegistreradArtikelLISTA" type="utreko:TidigareRabatterPaRegistreradArtikelLISTATYPE"></xs:element>');
        Schema.Append('<xs:complexType name="TidigareRabatterPaRegistreradArtikelLISTATYPE"><xs:sequence><xs:element ref="utreko:TidigareRabattPaRegistreradArtikel" maxOccurs="unbounded" /></xs:sequence>');
        Schema.Append('</xs:complexType><xs:element name="TotalForsaljningssummaForOlikaHuvudgrupper" type="utreko:TotalForsaljningssummaForOlikaHuvudgrupperTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="TotalForsaljningssummaForOlikaHuvudgrupperTYPE"><xs:sequence><xs:element ref="utreko:NamnPaHuvudgrupp" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotalForsaljningssummaForHuvudgrupp" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="TotalForsaljningssummaPerBetalningsmedel" type="utreko:TotalForsaljningssummaPerBetalningsmedelTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="TotalForsaljningssummaPerBetalningsmedelTYPE"><xs:sequence><xs:element ref="utreko:Betalningsmedel" />');
        Schema.Append('<xs:element ref="utreko:ForsaljningssummaPerBetalningsmedel" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="TotalaForsaljningsbeloppIUtlandskValutaLISTA" type="utreko:TotalaForsaljningsbeloppIUtlandskValutaLISTATYPE"></xs:element>');
        Schema.Append('<xs:complexType name="TotalaForsaljningsbeloppIUtlandskValutaLISTATYPE"><xs:sequence><xs:element ref="utreko:TotaltForsaljningsbeloppIUtlandskValuta" maxOccurs="unbounded" />');
        Schema.Append('</xs:sequence></xs:complexType><xs:element name="TotalaForsaljningssummorForOlikaHuvudgrupperLISTA" type="utreko:TotalaForsaljningssummorForOlikaHuvudgrupperLISTATYPE">');
        Schema.Append('</xs:element><xs:complexType name="TotalaForsaljningssummorForOlikaHuvudgrupperLISTATYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:TotalForsaljningssummaForOlikaHuvudgrupper" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="TotalaForsaljningssummorPerBetalningsmedelLISTA" type="utreko:TotalaForsaljningssummorPerBetalningsmedelLISTATYPE"></xs:element>');
        Schema.Append('<xs:complexType name="TotalaForsaljningssummorPerBetalningsmedelLISTATYPE"><xs:sequence><xs:element ref="utreko:TotalForsaljningssummaPerBetalningsmedel" maxOccurs="unbounded" />');
        Schema.Append('</xs:sequence></xs:complexType><xs:element name="TotaltForsaljningsbeloppIUtlandskValuta" type="utreko:TotaltForsaljningsbeloppIUtlandskValutaTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="TotaltForsaljningsbeloppIUtlandskValutaTYPE"><xs:sequence><xs:element ref="utreko:UtlandskValuta" /><xs:element ref="utreko:BeloppIUtlandskValuta" />');
        Schema.Append('</xs:sequence></xs:complexType><xs:element name="ValdPeriodForExportAvDataFranJournalminne" type="utreko:ValdPeriodForExportAvDataFranJournalminneTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="ValdPeriodForExportAvDataFranJournalminneTYPE"><xs:sequence><xs:element ref="utreko:ValdStarttidpunktForExportAvDataFranJournalminnet" />');
        Schema.Append('<xs:element ref="utreko:ValdSluttidpunktForExportAvDataFranJournalminnet" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="VaxelkassaIUtlandskValuta" type="utreko:VaxelkassaIUtlandskValutaTYPE"></xs:element><xs:complexType name="VaxelkassaIUtlandskValutaTYPE"><xs:sequence>');
        Schema.Append('<xs:element ref="utreko:UtlandskValuta" /><xs:element ref="utreko:BeloppIUtlandskValuta" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="VaxelkassorIUtlandskValutaLISTA" type="utreko:VaxelkassorIUtlandskValutaLISTATYPE"></xs:element><xs:complexType name="VaxelkassorIUtlandskValutaLISTATYPE">');
        Schema.Append('<xs:sequence><xs:element ref="utreko:VaxelkassaIUtlandskValuta" maxOccurs="unbounded" /></xs:sequence></xs:complexType>');
        Schema.Append('<xs:element name="VerifieringAvKvittodataMellanKontrollprogramOchKontrollserver" type="utreko:VerifieringAvKvittodataMellanKontrollprogramOchKontrollserverTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="VerifieringAvKvittodataMellanKontrollprogramOchKontrollserverTYPE"><xs:sequence><xs:element ref="utreko:LopnummerForKassakvitto" />');
        Schema.Append('<xs:element ref="utreko:Avstamningskod" /></xs:sequence></xs:complexType><xs:element name="XDagrapport" type="utreko:XDagrapportTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="XDagrapportTYPE"><xs:sequence><xs:element ref="utreko:ForetagetsNamn" /><xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" />');
        Schema.Append('<xs:element ref="utreko:DatumOchKlockslagNarRapportFramstalls" /><xs:element ref="utreko:Kassabeteckning" /><xs:element ref="utreko:TotalForsaljningssumma" />');
        Schema.Append('<xs:element ref="utreko:TotalaForsaljningssummorForOlikaHuvudgrupperLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattPaOlikaSkattesatserLISTA" />');
        Schema.Append('<xs:element ref="utreko:VaxelkassansBeloppISvenskaKronor" /><xs:element ref="utreko:VaxelkassorIUtlandskValutaLISTA" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:AntalSaldaVaror" minOccurs="0" /><xs:element ref="utreko:AntalSaldaTjanster" minOccurs="0" /><xs:element ref="utreko:AntalKassakvitton" />');
        Schema.Append('<xs:element ref="utreko:AntalKassaladoppningar" minOccurs="0" /><xs:element ref="utreko:AntalKvittokopior" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppPaKvittokopior" minOccurs="0" /><xs:element ref="utreko:AntalKvittonSomTagitsFramIOvningslage" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppIOvningslage" minOccurs="0" /><xs:element ref="utreko:TotalaForsaljningssummorPerBetalningsmedelLISTA" />');
        Schema.Append('<xs:element ref="utreko:AntalReturer" /><xs:element ref="utreko:ReturernasBelopp" /><xs:element ref="utreko:RabatternasBelopp" />');
        Schema.Append('<xs:element ref="utreko:AntalOvrigaRegistreringarSomMinskatDagensForsaljningsbelopp" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppAvOvrigaRegistreringarSomMinskatDagensForsaljningsbelopp" /><xs:element ref="utreko:AntalOavslutadeForsaljningar" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppAvOavslutadeForsaljningar" /><xs:element ref="utreko:GrandTotalForsaljning" /><xs:element ref="utreko:GrandTotalRetur" />');
        Schema.Append('<xs:element ref="utreko:GrandTotalNetto" /></xs:sequence></xs:complexType><xs:element name="ZDagrapport" type="utreko:ZDagrapportTYPE"></xs:element>');
        Schema.Append('<xs:complexType name="ZDagrapportTYPE"><xs:sequence><xs:element ref="utreko:ForetagetsNamn" /><xs:element ref="utreko:OrganisationsnummerEllerPersonnummer" />');
        Schema.Append('<xs:element ref="utreko:DatumOchKlockslagNarRapportFramstalls" /><xs:element ref="utreko:LopnummerForZDagrapport" /><xs:element ref="utreko:Kassabeteckning" />');
        Schema.Append('<xs:element ref="utreko:TillverkningsnummerForKassaregistret" /><xs:element ref="utreko:ModellbeteckningForKassaregistret" />');
        Schema.Append('<xs:element ref="utreko:ModellEllerProgramForKassaregistret" /><xs:element ref="utreko:VersionsnummerForKassaregistret" /><xs:element ref="utreko:TotalForsaljningssumma" />');
        Schema.Append('<xs:element ref="utreko:TotalaForsaljningssummorForOlikaHuvudgrupperLISTA" minOccurs="0" /><xs:element ref="utreko:MervardesskattPaOlikaSkattesatserLISTA" />');
        Schema.Append('<xs:element ref="utreko:VaxelkassansBeloppISvenskaKronor" /><xs:element ref="utreko:VaxelkassorIUtlandskValutaLISTA" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:AntalSaldaVaror" minOccurs="0" /><xs:element ref="utreko:AntalSaldaTjanster" minOccurs="0" /><xs:element ref="utreko:AntalKassakvitton" />');
        Schema.Append('<xs:element ref="utreko:AntalKassaladoppningar" minOccurs="0" /><xs:element ref="utreko:AntalKvittokopior" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppPaKvittokopior" minOccurs="0" /><xs:element ref="utreko:AntalKvittonSomTagitsFramIOvningslage" minOccurs="0" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppIOvningslage" minOccurs="0" /><xs:element ref="utreko:TotalaForsaljningssummorPerBetalningsmedelLISTA" />');
        Schema.Append('<xs:element ref="utreko:AntalReturer" /><xs:element ref="utreko:ReturernasBelopp" /><xs:element ref="utreko:RabatternasBelopp" />');
        Schema.Append('<xs:element ref="utreko:AntalOvrigaRegistreringarSomMinskatDagensForsaljningsbelopp" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppAvOvrigaRegistreringarSomMinskatDagensForsaljningsbelopp" /><xs:element ref="utreko:AntalOavslutadeForsaljningar" />');
        Schema.Append('<xs:element ref="utreko:TotaltBeloppAvOavslutadeForsaljningar" /><xs:element ref="utreko:GrandTotalForsaljning" /><xs:element ref="utreko:GrandTotalRetur" />');
        Schema.Append('<xs:element ref="utreko:GrandTotalNetto" /></xs:sequence></xs:complexType></xs:schema>');
    end;
}
