/** Defines locations */
export const DRAGONGLASS_RESTAURANT_DEFINE_LAYOUT = "DRAGONGLASS_RESTAURANT_DEFINE_LAYOUT";

/** Selects active restaurant */
export const DRAGONGLASS_RESTAURANT_SELECT_RESTAURANT = "DRAGONGLASS_RESTAURANT_SELECT_RESTAURANT";

/** Selects active location */
export const DRAGONGLASS_RESTAURANT_SELECT_LOCATION = "DRAGONGLASS_RESTAURANT_SELECT_LOCATION";

/** Defines waiter pad data */
export const DRAGONGLASS_RESTAURANT_DEFINE_WAITERPADS = "DRAGONGLASS_RESTAURANT_DEFINE_WAITERPADS";

/** Selects active waiter pad */
export const DRAGONGLASS_RESTAURANT_SELECT_WAITERPAD = "DRAGONGLASS_RESTAURANT_SELECT_WAITERPAD";

/** Updates status of a seating (table) or a waiter pad */
export const DRAGONGLASS_RESTAURANT_UPDATE_STATUS = "DRAGONGLASS_RESTAURANT_UPDATE_STATUS";

/** Shows menu for a table */
export const DRAGONGLASS_RESTAURANT_SELECT_TABLE = "DRAGONGLASS_RESTAURANT_SELECT_TABLE";

/** Define statuses (table and waiter pad) */
export const DRAGONGLASS_RESTAURANT_DEFINE_STATUSES = "DRAGONGLASS_RESTAURANT_DEFINE_STATUSES";

/** Define statuses (table and waiter pad) */
export const DRAGONGLASS_RESTAURANT_UPDATE_GUESTS = "DRAGONGLASS_RESTAURANT_UPDATE_GUESTS";
