export const DRAGONGLASS_TEXTENTER_OPEN = "DRAGONGLASS_TEXTENTER_OPEN";
export const DRAGONGLASS_TEXTENTER_CLOSE = "DRAGONGLASS_TEXTENTER_CLOSE";
export const DRAGONGLASS_TEXTENTER_REMOVE = "DRAGONGLASS_TEXTENTER_REMOVE";
