export const MOBILE_BUTTON_VIEW = {
  LIST: "MOBILE_BUTTON_VIEW.LIST",
  GRID: "MOBILE_BUTTON_VIEW.GRID",
  GRID_SMALL: "MOBILE_BUTTON_VIEW.GRID_SMALL",
  COLUMNS: "MOBILE_BUTTON_VIEW.COLUMNS",
};

export const MOBILE_BUTTON_OTHER = {
  SEARCH: "MOBILE_BUTTON_OTHER.SEARCH",
};

export const MOBILE_SEARCH_TYPES = {
  ITEM: "ITEM",
};
