export const DRAGONGLASS_NAV_EVENTS_QUEUE_UPDATE = "DRAGONGLASS_NAV_EVENTS_QUEUE_UPDATE";
export const DRAGONGLASS_NAV_EVENTS_START = "DRAGONGLASS_NAV_EVENTS_UPDATE";
export const DRAGONGLASS_NAV_EVENTS_END = "DRAGONGLASS_NAV_EVENTS_END";
export const DRAGONGLASS_NAV_EVENTS_CLEAR = "DRAGONGLASS_NAV_EVENTS_CLEAR";