### Create a PersonGroup
PUT https://northeurope.api.cognitive.microsoft.com/face/v1.0/persongroups/g0000022
Content-Type: application/json
Ocp-Apim-Subscription-Key: 8bbe2f04fa3e4160b76d60220e6d01a6

{"name":"CT1000025","userData":"tihana"}

### Get all PersonGroups
GET  https://northeurope.api.cognitive.microsoft.com/face/v1.0/persongroups/
Ocp-Apim-Subscription-Key: 8bbe2f04fa3e4160b76d60220e6d01a6

### Get all PersonGroups2
GET  https://northeurope.api.cognitive.microsoft.com/face/v1.0/persongroups/
Ocp-Apim-Subscription-Key: 8bbe2f04fa3e4160b76d60220e6d01a6

### Delete PersonGroup
DELETE   https://northeurope.api.cognitive.microsoft.com/face/v1.0/persongroups/ct1000062
Ocp-Apim-Subscription-Key: 8bbe2f04fa3e4160b76d60220e6d01a6

### Get Persons
GET https://northeurope.api.cognitive.microsoft.com/face/v1.0/persongroups/c000002/persons/c99be16d-2e39-49e1-80a7-e39bce7b4f2c
Content-Type: application/json
Ocp-Apim-Subscription-Key: 8bbe2f04fa3e4160b76d60220e6d01a6


### Add Face
POST https://northeurope.api.cognitive.microsoft.com/face/v1.0/persongroups/c000002/persons/9dd8af36-fba8-4307-a2ae-b0b69cb9a0c7/persistedFaces
Ocp-Apim-Subscription-Key: 8bbe2f04fa3e4160b76d60220e6d01a6

--data-ascii "{body}" 