name: 'Prerelease'
run-name: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'Application/**'
      - 'Test/**'
      - 'Performance Toolkit/**'
      - '.github/**'

concurrency:
  group: 'ci-${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}'

defaults:
  run:
    shell: powershell

permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  Run:
    uses: navipartner/devops/.github/workflows/MainWorkflow.yaml@main
    secrets: inherit
    with:
      pipelineType: prerelease