name: 'Release'
run-name: '${{ github.workflow }} ${{ github.ref_name }}'

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  Run:
    uses: navipartner/devops/.github/workflows/MainWorkflow.yaml@main
    secrets: inherit
    with:
      pipelineType: release