codeunit 6184672 "NPR DK SAF-T Cash Export Mgt."
{
    Access = Internal;
    TableNo = "NPR DK SAF-T Cash Exp. Header";

    trigger OnRun()
    begin
        StartExport(Rec);
    end;

    var
        CancelExportIsInProgressQst: Label 'Do you want to cancel all export jobs and restart?';
        DeleteExportIsInProgressQst: Label 'Do you want to delete the export entry?';
        ExportIsCompletedQst: Label 'The export was completed. You can download the export result choosing the Download SAF-T File action.\';
        ExportIsInProgressMsg: Label 'The export is in progress. Starting a new job cancels the current progress.\';
        GenerateSAFTFileImmediatelyQst: Label 'Since you did not schedule the SAF-T file generation, it will be generated immediately which can take a while. Do you want to continue?';
        LegacyMasterDataOnlyErr: Label 'This export was generated by an earlier version and contains only master data, without the cash register transactions. Restart the export to generate a single SAF-T file.';
        LegacyMultipleFilesTitleLbl: Label 'The export must be restarted';
        LegacyMultipleFilesErr: Label 'This export was generated as multiple SAF-T files, which the Danish Tax Authorities do not accept. Restart the export to generate a single SAF-T file.';
        LinesInProgressOrCompletedMsg: Label 'One or more export lines are in progress or completed.\';
        NoErrorMessageErr: Label 'The generation of a SAF-T file failed but no error message was logged.';
        NoFileGeneratedErr: Label 'No SAF-T file has been generated.';
        NotPossibleToScheduleMsg: Label 'You are not allowed to schedule the SAF-T file generation';
        ParallelSAFTFileGenerationTxt: Label 'Background SAF-T file generation';
        RestartExportLineQst: Label 'Do you want to restart the export for this line?';
        RestartExportActionLbl: Label 'Restart export';
        RestartExportQst: Label 'Do you want to restart the export to get a new SAF-T file?';
        SAFTFileGeneratedTxt: Label 'SAF-T file generated.';
        SAFTFileNotGeneratedTxt: Label 'SAF-T file not generated.';
        ScheduleTaskForLineTxt: Label 'Schedule a task for line %1.', Comment = '%1 = number';
        SetStartDateTimeAsCurrentQst: Label 'The Earliest Start Date/Time field is not filled in. Do you want to proceed and start the export immediately?';
        ElectronicJournalLbl: Label 'Electronic journal from %1 to %2', Comment = '%1 = starting date, %2 = ending date';
        XmlFileFilterTxt: Label 'XML File (*.xml)|*.xml', Locked = true;
        XmlFileSaveDialogTxt: Label 'Export SAF-T file';

    local procedure StartExport(var SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        TypeHelper: Codeunit "Type Helper";
    begin
        if not PrepareForExport(SAFTExportHeader) then
            exit;

        CreateExportLine(SAFTExportHeader);

        SAFTExportHeader.Validate(Status, SAFTExportHeader.Status::"In Progress");
        SAFTExportHeader.Validate("Execution Start Date/Time", TypeHelper.GetCurrentDateTimeInUserTimeZone());
        SAFTExportHeader.Validate("Execution End Date/Time", 0DT);
        SAFTExportHeader.Modify(true);

        Commit();

        StartExportLines(SAFTExportHeader);
        SAFTExportHeader.Find();
    end;

    internal procedure DeleteExport(var SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
    begin
        if not CheckStatus(SAFTExportHeader.Status, DeleteExportIsInProgressQst) then
            exit;

        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        SAFTExportLine.SetRange(Status, SAFTExportLine.Status::"In Progress");
        if SAFTExportLine.FindSet() then
            repeat
                CancelTask(SAFTExportLine);
            until SAFTExportLine.Next() = 0;

        SAFTExportLine.SetRange(Status);
        SAFTExportLine.DeleteAll(true);
    end;

    internal procedure ThrowNoParallelExecutionNotification()
    var
        ParallelExecutionNotification: Notification;
    begin
        ParallelExecutionNotification.Message := NotPossibleToScheduleMsg;
        ParallelExecutionNotification.Scope := NotificationScope::LocalScope;
        ParallelExecutionNotification.Send();
    end;

    internal procedure RestartTaskOnExportLine(var SAFTExportLine: Record "NPR DK SAF-T Cash Export Line")
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
    begin
        if not CheckLineStatusForRestart(SAFTExportLine) then
            exit;

        if not SAFTExportLine.FindSet() then
            exit;

        repeat
            CancelTask(SAFTExportLine);
            SAFTExportHeader.Get(SAFTExportLine.ID);
            RunGenerateSAFTFileOnSingleLine(SAFTExportLine, CurrentDateTime(), SAFTExportHeader);
            SAFTExportHeader.Find();
            UpdateExportStatus(SAFTExportHeader);
        until SAFTExportLine.Next() = 0;
    end;

    internal procedure UpdateExportStatus(var SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
        TypeHelper: Codeunit "Type Helper";
        Status: Enum "NPR DK SAF-T Cash Exp. Status";
        TotalCount: Integer;
    begin
        if SAFTExportHeader.ID = 0 then
            exit;

        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        TotalCount := SAFTExportLine.Count();
        SAFTExportLine.SetRange(Status, SAFTExportLine.Status::Completed);
        if SAFTExportLine.Count() = TotalCount then begin
            SAFTExportHeader.Validate(Status, SAFTExportHeader.Status::Completed);
            SAFTExportHeader.Validate("Execution End Date/Time", TypeHelper.GetCurrentDateTimeInUserTimeZone());
            SAFTExportHeader.Modify(true);
            exit;
        end;

        SAFTExportLine.SetRange(Status, SAFTExportLine.Status::Failed);
        if SAFTExportLine.IsEmpty() then
            Status := SAFTExportHeader.Status::"In Progress"
        else
            Status := SAFTExportHeader.Status::Failed;

        SAFTExportHeader.Validate(Status, Status);
        SAFTExportHeader.Modify(true);
    end;

    internal procedure ShowActivityLog(SAFTExportLine: Record "NPR DK SAF-T Cash Export Line")
    var
        ActivityLog: Record "Activity Log";
        ActivityLogPage: Page "Activity Log";
    begin
        ActivityLog.SetRange("Record ID", SAFTExportLine.RecordId());
        ActivityLogPage.SetTableView(ActivityLog);
        ActivityLogPage.Run();
    end;

    internal procedure ShowErrorOnExportLine(SAFTExportLine: Record "NPR DK SAF-T Cash Export Line")
    var
        ActivityLog: Record "Activity Log";
        Stream: InStream;
        ErrorMessage: Text;
    begin
        ActivityLog.SetRange("Record ID", SAFTExportLine.RecordId());
        if not ActivityLog.FindLast() or (ActivityLog.Status <> ActivityLog.Status::Failed) then
            exit;

        ActivityLog.CalcFields("Detailed Info");
        if not ActivityLog."Detailed Info".HasValue() then
            Error(NoErrorMessageErr);

        ActivityLog."Detailed Info".CreateInStream(Stream);
        Stream.ReadText(ErrorMessage);
        if ErrorMessage = '' then
            Error(NoErrorMessageErr);

        Message(ErrorMessage);
    end;

    internal procedure LogSuccess(SAFTExportLine: Record "NPR DK SAF-T Cash Export Line")
    var
        ActivityLog: Record "Activity Log";
    begin
        ActivityLog.LogActivity(SAFTExportLine.RecordId(), ActivityLog.Status::Success, '', SAFTFileGeneratedTxt, '');
    end;

    internal procedure LogError(SAFTExportLine: Record "NPR DK SAF-T Cash Export Line")
    var
        ActivityLog: Record "Activity Log";
        ErrorMessage: Text;
    begin
        ErrorMessage := GetLastErrorText();
        ActivityLog.LogActivity(SAFTExportLine.RecordId(), ActivityLog.Status::Failed, '', SAFTFileNotGeneratedTxt, ErrorMessage);
        ActivityLog.SetDetailedInfoFromText(ErrorMessage);
    end;

    local procedure LogState(SAFTExportLine: Record "NPR DK SAF-T Cash Export Line"; Description: Text[250])
    var
        ActivityLog: Record "Activity Log";
    begin
        ActivityLog.LogActivity(SAFTExportLine.RecordId(), ActivityLog.Status::Success, '', ParallelSAFTFileGenerationTxt, Description);
    end;

    local procedure StartExportLines(SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
    begin
        SAFTExportLine.LockTable();
        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        SAFTExportLine.FindSet();
        repeat
            RunGenerateSAFTFileOnSingleLine(SAFTExportLine, SAFTExportHeader."Earliest Start Date/Time", SAFTExportHeader);
        until SAFTExportLine.Next() = 0;
    end;

    local procedure RunGenerateSAFTFileOnSingleLine(var SAFTExportLine: Record "NPR DK SAF-T Cash Export Line"; NotBefore: DateTime; SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        DoNotScheduleTask: Boolean;
        TaskID: Guid;
    begin
        SAFTExportLine.Validate(Status, SAFTExportLine.Status::"In Progress");
        Clear(SAFTExportLine."SAF-T File");
        SAFTExportLine.Validate(Progress, 0);
        if SAFTExportHeader."Parallel Processing" then begin
            LogState(SAFTExportLine, StrSubstNo(ScheduleTaskForLineTxt, SAFTExportLine."Line No."));

            OnBeforeScheduleTask(DoNotScheduleTask, TaskID);
            if DoNotScheduleTask then
                SAFTExportLine."Task ID" := TaskID
            else
                SAFTExportLine."Task ID" :=
                    TaskScheduler.CreateTask(
                        Codeunit::"NPR DK Gen. SAF-T Cash File", Codeunit::"NPR DK SAF-T Exp. Err. Handler", true, CompanyName(),
                        NotBefore, SAFTExportLine.RecordId());
            SAFTExportLine.Modify(true);
            Commit();
            exit;
        end;
        SAFTExportLine."Task ID" := CreateGuid();
        SAFTExportLine.Modify(true);
        Commit();

        ClearLastError();
        if not Codeunit.Run(Codeunit::"NPR DK Gen. SAF-T Cash File", SAFTExportLine) then
            Codeunit.Run(Codeunit::"NPR DK SAF-T Exp. Err. Handler", SAFTExportLine);
        Commit();
    end;

    local procedure PrepareForExport(var SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header"): Boolean
    var
        ErrorMessageHandler: Codeunit "Error Message Handler";
        ErrorMessageManagement: Codeunit "Error Message Management";
        SAFTExportCheck: Codeunit "NPR DK SAF-T Cash Export Check";
    begin
        ErrorMessageManagement.Activate(ErrorMessageHandler);
        SAFTExportCheck.Run(SAFTExportHeader);
        if ErrorMessageManagement.GetLastErrorID() <> 0 then begin
            ErrorMessageHandler.ShowErrors();
            exit(false);
        end;

        if SAFTExportHeader.Status = SAFTExportHeader.Status::"In Progress" then
            if HandleConfirm(StrSubstNo('%1%2', ExportIsInProgressMsg, CancelExportIsInProgressQst)) then
                RemoveExportLines(SAFTExportHeader)
            else
                exit(false);

        if SAFTExportHeader.Status = SAFTExportHeader.Status::Completed then
            if not HandleConfirm(StrSubstNo('%1%2', ExportIsCompletedQst, RestartExportQst)) then
                exit(false);

        if (SAFTExportHeader."Parallel Processing") and (SAFTExportHeader."Earliest Start Date/Time" = 0DT) then begin
            if not HandleConfirm(SetStartDateTimeAsCurrentQst) then
                exit(false);

            SAFTExportHeader."Earliest Start Date/Time" := CurrentDateTime();
        end;
        if not SAFTExportHeader."Parallel Processing" then
            if not HandleConfirm(GenerateSAFTFileImmediatelyQst) then
                exit(false);

        exit(true)
    end;

    local procedure CreateExportLine(SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
    begin
        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        SAFTExportLine.DeleteAll(true);

        SAFTExportLine.Init();
        SAFTExportLine.Validate(ID, SAFTExportHeader.ID);
        SAFTExportLine.Validate("Line No.", 1);
        SAFTExportLine.Validate(Description,
            CopyStr(StrSubstNo(ElectronicJournalLbl, SAFTExportHeader."Starting Date", SAFTExportHeader."Ending Date"), 1, MaxStrLen(SAFTExportLine.Description)));
        SAFTExportLine.Validate("Starting Date", SAFTExportHeader."Starting Date");
        SAFTExportLine.Validate("Ending Date", SAFTExportHeader."Ending Date");
        SAFTExportLine.Insert(true);
    end;

    local procedure RemoveExportLines(var SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
    begin
        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        if not SAFTExportLine.FindSet() then
            exit;

        repeat
            RemoveExportLine(SAFTExportLine);
        until SAFTExportLine.Next() = 0;
    end;

    local procedure RemoveExportLine(var SAFTExportLine: Record "NPR DK SAF-T Cash Export Line")
    begin
        CancelTask(SAFTExportLine);
        SAFTExportLine.Delete(true);
    end;

    local procedure CancelTask(SAFTExportLine: Record "NPR DK SAF-T Cash Export Line")
    var
        DoNotCancelTask: Boolean;
    begin
        if IsNullGuid(SAFTExportLine."Task ID") then
            exit;

        OnBeforeCancelTask(DoNotCancelTask);
        if not DoNotCancelTask then
            if TaskScheduler.TaskExists(SAFTExportLine."Task ID") then
                TaskScheduler.CancelTask(SAFTExportLine."Task ID");
    end;

    internal procedure DownloadSAFTFile(SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header")
    var
        CompanyInformation: Record "Company Information";
        SAFTExportLine: Record "NPR DK SAF-T Cash Export Line";
        SAFTXMLHelper: Codeunit "NPR DK SAF-T XML Helper";
        FileInStream: InStream;
        FileName: Text;
    begin
        SAFTExportLine.SetRange(ID, SAFTExportHeader.ID);
        if SAFTExportLine.Count() > 1 then
            ThrowLegacyExportError(SAFTExportHeader, LegacyMultipleFilesErr);
#pragma warning disable AL0432
        SAFTExportLine.SetRange("Master Data", true);
        if not SAFTExportLine.IsEmpty() then
            ThrowLegacyExportError(SAFTExportHeader, LegacyMasterDataOnlyErr);
        SAFTExportLine.SetRange("Master Data");
#pragma warning restore AL0432

        SAFTExportLine.SetAutoCalcFields("SAF-T File");
        if not SAFTExportLine.FindFirst() then
            Error(NoFileGeneratedErr);
        if (SAFTExportLine.Status <> SAFTExportLine.Status::Completed) or (not SAFTExportLine."SAF-T File".HasValue()) then
            Error(NoFileGeneratedErr);

        CompanyInformation.Get();
        FileName := SAFTXMLHelper.GetFilePath(CompanyInformation."VAT Registration No.", SAFTExportLine."Created Date/Time", 1, 1);
        SAFTExportLine."SAF-T File".CreateInStream(FileInStream, TextEncoding::UTF8);
        DownloadFromStream(FileInStream, XmlFileSaveDialogTxt, '', XmlFileFilterTxt, FileName);
    end;

    local procedure ThrowLegacyExportError(SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header"; ErrorMessage: Text)
    var
        LegacyMultipleFilesError: ErrorInfo;
    begin
        LegacyMultipleFilesError := ErrorInfo.Create(ErrorMessage);
        LegacyMultipleFilesError.Title := LegacyMultipleFilesTitleLbl;
        LegacyMultipleFilesError.RecordId := SAFTExportHeader.RecordId();
        LegacyMultipleFilesError.AddAction(RestartExportActionLbl, Codeunit::"NPR DK SAF-T Cash Export Mgt.", 'RestartExportFromErrorInfo');
        Error(LegacyMultipleFilesError);
    end;

    procedure RestartExportFromErrorInfo(LegacyMultipleFilesError: ErrorInfo)
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
    begin
        SAFTExportHeader.Get(LegacyMultipleFilesError.RecordId);
        Codeunit.Run(Codeunit::"NPR DK SAF-T Cash Export Mgt.", SAFTExportHeader);
    end;

    local procedure HandleConfirm(ConfirmText: Text): Boolean
    begin
        if not GuiAllowed() then
            exit(true);

        exit(Confirm(ConfirmText, false));
    end;

    local procedure CheckStatus(Status: Enum "NPR DK SAF-T Cash Exp. Status"; Question: Text): Boolean
    var
        SAFTExportHeader: Record "NPR DK SAF-T Cash Exp. Header";
        StatusMessage: Text;
    begin
        if Status = SAFTExportHeader.Status::"In Progress" then
            StatusMessage := ExportIsInProgressMsg;
        if Status = SAFTExportHeader.Status::Completed then
            StatusMessage := ExportIsCompletedQst;

        if StatusMessage <> '' then
            exit(HandleConfirm(StatusMessage + Question));

        exit(true);
    end;

    local procedure CheckLineStatusForRestart(var SAFTExportLine: Record "NPR DK SAF-T Cash Export Line"): Boolean;
    begin
        SAFTExportLine.SetFilter(Status, '%1|%2', SAFTExportLine.Status::Failed, SAFTExportLine.Status::Completed);
        if not SAFTExportLine.IsEmpty() then
            exit(HandleConfirm(LinesInProgressOrCompletedMsg + RestartExportLineQst));

        exit(true);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeScheduleTask(var DoNotScheduleTask: Boolean; var TaskID: Guid)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCancelTask(var DoNotCancelTask: Boolean)
    begin
    end;
}
