page 6151326 "NPR DK SAF-T Cash Export Card"
{
    Extensible = False;
    Caption = 'SAF-T Cash Register Export';
    DataCaptionExpression = '';
    PageType = Card;
    SourceTable = "NPR DK SAF-T Cash Exp. Header";
    UsageCategory = None;

    layout
    {
        area(Content)
        {
            group(General)
            {
                field("Export Name Code"; Rec."Export Name Code")
                {
                    ApplicationArea = NPRDKFiscal;
                    ToolTip = 'Specifies the Export Name Code that represents the SAF-T reporting period.';
                }
                field(StartingDate; Rec."Starting Date")
                {
                    ApplicationArea = NPRDKFiscal;
                    ToolTip = 'Specifies the starting date of the SAF-T reporting period.';
                }
                field(EndingDate; Rec."Ending Date")
                {
                    ApplicationArea = NPRDKFiscal;
                    ToolTip = 'Specifies the ending date of the SAF-T reporting period.';
                }
                field(ParallelProcessing; Rec."Parallel Processing")
                {
                    ApplicationArea = NPRDKFiscal;
                    Enabled = IsParallelProcessingAllowed;
                    ToolTip = 'Specifies if the SAF-T file will be generated by a background job.';

                    trigger OnValidate()
                    begin
                        CalcParallelProcessingEnabled();
                        CurrPage.Update();
                    end;
                }
                field("Header Comment"; Rec."Header Comment")
                {
                    ApplicationArea = NPRDKFiscal;
                    ToolTip = 'Specifies the comment that is exported to the HeaderComment XML node of the SAF-T file';
                }
                field(EarliestStartDateTime; Rec."Earliest Start Date/Time")
                {
                    ApplicationArea = NPRDKFiscal;
                    Enabled = IsParallelProcessingEnabled;
                    ToolTip = 'Specifies the earliest date and time when the background job must be run.';
                }
                field(Status; Rec.Status)
                {
                    ApplicationArea = NPRDKFiscal;
                    ToolTip = 'Specifies the status of the SAF-T file generation.';
                }
                field(ExecutionStartDateTime; Rec."Execution Start Date/Time")
                {
                    ApplicationArea = NPRDKFiscal;
                    ToolTip = 'Specifies the date and time when the SAF-T file generation was started.';
                }
                field(ExecutionEndDateTime; Rec."Execution End Date/Time")
                {
                    ApplicationArea = NPRDKFiscal;
                    ToolTip = 'Specifies the date and time when the SAF-T file generation was completed.';
                }
            }
            part(ExportLines; "NPR DK SAF-T Cash Exp. Subpage")
            {
                ApplicationArea = NPRDKFiscal;
                SubPageLink = ID = field(ID);
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(Start)
            {
                ApplicationArea = NPRDKFiscal;
                Caption = 'Start';
                Image = Start;
                Promoted = true;
                PromotedCategory = Process;
                PromotedIsBig = true;
                PromotedOnly = true;
                ToolTip = 'Start the generation of the SAF-T file.';

                trigger OnAction()
                begin
                    Codeunit.Run(Codeunit::"NPR DK SAF-T Cash Export Mgt.", Rec);
                    CurrPage.Update();
                end;
            }
            action(DownloadFile)
            {
                ApplicationArea = NPRDKFiscal;
                Caption = 'Download File';
                Image = ExportFile;
                Promoted = true;
                PromotedCategory = Process;
                PromotedIsBig = true;
                PromotedOnly = true;
                ToolTip = 'Download the generated SAF-T file.';

                trigger OnAction()
                var
                    SAFTExportMgt: Codeunit "NPR DK SAF-T Cash Export Mgt.";
                begin
                    SAFTExportMgt.DownloadSAFTFile(Rec);
                end;
            }
        }
    }

    var
        IsParallelProcessingAllowed: Boolean;
        IsParallelProcessingEnabled: Boolean;

    trigger OnOpenPage()
    var
        SAFTExportMgt: Codeunit "NPR DK SAF-T Cash Export Mgt.";
    begin
        IsParallelProcessingAllowed := TaskScheduler.CanCreateTask();
        if not IsParallelProcessingAllowed then
            SAFTExportMgt.ThrowNoParallelExecutionNotification();
    end;

    trigger OnInsertRecord(BelowxRec: Boolean): Boolean
    begin
        IsParallelProcessingEnabled := TaskScheduler.CanCreateTask();
    end;

    trigger OnAfterGetCurrRecord()
    begin
        CalcParallelProcessingEnabled();
    end;

    local procedure CalcParallelProcessingEnabled()
    begin
        IsParallelProcessingEnabled := Rec."Parallel Processing";
    end;
}
