export const METHOD_EVENT_NAME = "OnInvokeMethod";
export const REJECT_DUPLICATE_THRESHOLD = 300;
export const SKIPPED_BUSY = "SKIPPED_BUSY";
export const REJECTED_DUPLICATE = "REJECTED_DUPLICATE";
export const INVOCATION_SUCCESSFUL = "INVOCATION_SUCCESSFUL";
export const INVOCATION_FAILED = "INVOCATION_FAILED";
